<?php
declare(strict_types=1);
header('Cache-Control: no-store, private, max-age=0');
header('Pragma: no-cache');
header('X-Content-Type-Options: nosniff');
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="dark">
<title>P2K · Max Rating Backfill</title>
<script src="config/site-branding.js?v=2.11.5-bf6a828490f57"></script>
<script src="assets/js/site-config.js?v=p2k-2.12.0-d025d8c46103-ae73ae796f09667d"></script>
<script src="assets/js/shared/api-cache.js?v=2.11.5-bf6a828490f57"></script>
<script src="assets/js/shared/api-request-semantics.js?v=2.11.5-bf6a828490f57"></script>
<script src="assets/js/shared/api-oauth-context.js?v=2.11.5-bf6a828490f57"></script>
<script src="assets/js/shared/api-transport.js?v=2.11.5-bf6a828490f57"></script>
<script src="assets/js/shared/api-request-coordinator.js?v=2.11.5-bf6a828490f57"></script>
<script src="assets/js/shared/api-client.js?v=2.11.5-bf6a828490f57"></script>
<script defer src="assets/js/shared/real-oauth.js?v=2.11.5-bf6a828490f57"></script>
<script src="assets/js/shared/team-points-client.js?v=2.11.5-bf6a828490f57"></script>
<style>
:root{font-family:Inter,Arial,sans-serif;color:#eee;background:#111}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#24201a,#111 42%);min-height:100vh}main{max-width:1000px;margin:0 auto;padding:28px 18px 60px}h1{margin:0 0 5px;font-size:28px;color:#f4b23e}.sub{margin:0 0 22px;color:#bbb}.card{border:1px solid #4c4335;background:#191713;border-radius:12px;padding:18px;margin:14px 0;box-shadow:0 8px 28px #0005}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}.metric{background:#242019;border:1px solid #3f372c;border-radius:9px;padding:12px}.metric span{display:block;color:#aaa;font-size:12px}.metric strong{display:block;margin-top:4px;font-size:22px}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.grow{flex:1 1 300px}button,select{border:1px solid #80662e;background:#2a2419;color:#fff;border-radius:8px;padding:9px 13px;font:inherit}button{cursor:pointer}button.primary{background:#8b5e10;border-color:#d69a24}button:disabled{opacity:.45;cursor:not-allowed}progress{width:100%;height:18px;accent-color:#d69a24}.status{white-space:pre-wrap;background:#0d0d0d;border:1px solid #333;border-radius:8px;padding:12px;min-height:72px;font-family:ui-monospace,Consolas,monospace;font-size:13px;color:#ddd}.note{color:#aaa;font-size:13px;line-height:1.45}.warn{color:#ffcc72}.ok{color:#8fe19c}.bad{color:#ff8c8c}#authBox{display:none}.hidden{display:none!important}
</style>
</head>
<body>
<main>
<h1>Max Rating Backfill</h1><p class="sub">Standalone one-time P2K maintenance tool · not linked from the normal interface.</p>
<section id="authBox" class="card"><h2>Administrator authentication required</h2><p>Sign in with the same Chess.com OAuth account used for P2K administration.</p><button id="loginButton" class="primary" type="button">Log in with Chess.com</button></section>
<div id="tool" class="hidden">
<section class="card"><div class="row"><strong id="identity">Authenticated administrator</strong><span class="grow"></span><button id="refreshButton" type="button">Refresh status</button></div><p class="note">The browser fetches Chess.com match details through the existing OAuth scheduler. P2K stores only rating-cap provenance. Historical responses that no longer expose the setting are recorded as <b>Unavailable</b>, never guessed from match names or player ratings.</p></section>
<section class="card"><div class="grid"><div class="metric"><span>Eligible matches</span><strong id="mTotal">—</strong></div><div class="metric"><span>Pending</span><strong id="mUnknown">—</strong></div><div class="metric"><span>Capped</span><strong id="mCapped">—</strong></div><div class="metric"><span>Open</span><strong id="mOpen">—</strong></div><div class="metric"><span>Unavailable</span><strong id="mUnavailable">—</strong></div><div class="metric"><span>Resolved</span><strong id="mResolved">—</strong></div></div><p class="note" id="finishedSummary"></p></section>
<section class="card"><div class="row"><label>Fetch batch <select id="batchSize"><option>100</option><option selected>250</option><option>500</option></select></label><button id="startButton" class="primary" type="button">Start / resume backfill</button><button id="pauseButton" type="button" disabled>Pause</button></div><div style="margin-top:14px"><progress id="progress" max="1" value="0"></progress></div><p class="note" id="throughput">Idle.</p><div id="statusLog" class="status">Initializing…</div></section>
</div>
</main>
<script>
(() => {
"use strict";
const ENDPOINT="server/team-points-green/public/max-rating-backfill.php",el=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat("en-GB").format(Number(n||0));
let client=null,api=null,running=false,controller=null,baselineResolved=0,startedAt=0,localFailures=0;
function log(message,kind=""){const stamp=new Date().toLocaleTimeString("en-GB",{hour12:false});el("statusLog").textContent=`[${stamp}] ${message}\n`+el("statusLog").textContent.slice(0,7000);el("statusLog").className=`status ${kind}`;}
function compactPayload(data){const rawTeams=data?.teams,sourceTeams=Array.isArray(rawTeams)?rawTeams:(rawTeams&&typeof rawTeams==="object"?Object.values(rawTeams):[]),teams=sourceTeams.filter(team=>team&&typeof team==="object").map(team=>({"@id":team?.["@id"]||"",url:team?.url||"",name:team?.name||""}));const out={teams,status:data?.status||"",settings:{}};if(data?.settings&&typeof data.settings==="object"){for(const key of ["max_rating","maxRating","time_class","time_control","rules"])if(Object.prototype.hasOwnProperty.call(data.settings,key))out.settings[key]=data.settings[key];}if(Object.prototype.hasOwnProperty.call(data||{},"max_rating"))out.max_rating=data.max_rating;return out;}
async function adminRequest(action,{method="GET",body=null,params={},timeoutMs=120000}={}){return client.endpointRequest(ENDPOINT,{action,method,body,params,timeoutMs,serverTrafficClass:"background"});}
function render(s={}){el("mTotal").textContent=fmt(s.total);el("mUnknown").textContent=fmt(s.unknown);el("mCapped").textContent=fmt(s.capped);el("mOpen").textContent=fmt(s.open_matches);el("mUnavailable").textContent=fmt(s.unavailable);el("mResolved").textContent=`${fmt(s.resolved)} · ${Number(s.resolved_percent||0).toFixed(1)}%`;el("finishedSummary").textContent=`Finished matches: ${fmt(s.finished)} · pending ${fmt(s.finished_unknown)} · capped ${fmt(s.finished_capped)} · open ${fmt(s.finished_open)} · unavailable ${fmt(s.finished_unavailable)}.`;el("progress").max=Math.max(1,Number(s.total||1));el("progress").value=Math.max(0,Number(s.resolved||0));if(running&&startedAt){const done=Math.max(0,Number(s.resolved||0)-baselineResolved),seconds=Math.max(.1,(Date.now()-startedAt)/1000),rate=done/seconds,eta=rate>0?Math.max(0,Number(s.unknown||0))/rate:null;el("throughput").textContent=`This session: ${fmt(done)} resolved · ${rate.toFixed(1)} matches/s${eta!==null?` · estimated remaining ${Math.ceil(eta)} s`:""} · fetch failures ${fmt(localFailures)}.`;}}
async function refresh(){const payload=await adminRequest("status");render(payload.snapshot);return payload.snapshot;}
async function ingestSucceeded(entries){const rows=entries.map(entry=>({match_id:Number(entry.item.match_id),payload:entry.value.payload}));let accepted=0;for(let i=0;i<rows.length;i+=50){const chunk=rows.slice(i,i+50);const result=await adminRequest("ingest",{method:"POST",body:{rows:chunk}});accepted+=Number(result.accepted||0);const rejected=(result.results||[]).filter(row=>row?.ok===false);if(rejected.length)log(`${rejected.length} server-side rows were rejected; first: ${rejected[0].error||"unknown error"}`,"bad");}return accepted;}
async function markPermanentFailures(failures){const ids=failures.filter(entry=>[404,410].includes(Number(entry?.error?.status))).map(entry=>Number(entry.item?.match_id)).filter(Boolean);if(!ids.length)return 0;const result=await adminRequest("mark-unavailable",{method:"POST",body:{match_ids:ids}});return Number(result.changed||0);}
async function run(){if(running)return;running=true;controller=new AbortController();localFailures=0;el("startButton").disabled=true;el("pauseButton").disabled=false;el("batchSize").disabled=true;try{let snapshot=await refresh();baselineResolved=Number(snapshot.resolved||0);startedAt=Date.now();if(Number(snapshot.unknown||0)===0){log("No pending max-rating rows remain.","ok");return;}log(`Starting with ${fmt(snapshot.unknown)} pending matches.`);while(running&&!controller.signal.aborted){const limit=Number(el("batchSize").value||250),candidatePayload=await adminRequest("candidates",{params:{limit}}),candidates=Array.isArray(candidatePayload.rows)?candidatePayload.rows:[];if(!candidates.length){log("No pending candidates remain.","ok");break;}const result=await api.processPriority(candidates,async item=>{const detail=await api.jsonDetailed(String(item.api_url),{cacheMode:"no-store",attempts:3,signal:controller.signal,priority:item.status==="registered"?100:item.status==="in_progress"?80:10,trafficClass:"background"});return {payload:compactPayload(detail.data)};},{signal:controller.signal,getKey:item=>String(item.api_url),getPriority:item=>item.status==="registered"?100:item.status==="in_progress"?80:10,onProgress:p=>{if(p.state==="failed")localFailures++;el("throughput").textContent=`Fetching batch: ${fmt(p.settled)} / ${fmt(p.total)} settled · ${fmt(p.failed)} failed.`;}});if(result.succeeded.length){const accepted=await ingestSucceeded(result.succeeded);log(`Fetched ${result.succeeded.length}; stored ${accepted} rating-cap observations.`);}const terminal=await markPermanentFailures(result.failures);if(terminal)log(`Marked ${terminal} permanently unavailable (HTTP 404/410).`,"warn");snapshot=await refresh();if(result.cancelled||controller.signal.aborted)break;if(!result.succeeded.length&&result.failures.length){log("This batch produced no successful Chess.com responses. Stopping to avoid a retry loop.","bad");break;}if(Number(snapshot.unknown||0)===0){log("Backfill queue is complete.","ok");break;}}}catch(error){if(error?.name==="AbortError"||controller?.signal.aborted)log("Backfill paused.");else{log(`Backfill stopped: ${error?.message||error}`,"bad");console.error(error);}}finally{running=false;el("startButton").disabled=false;el("pauseButton").disabled=true;el("batchSize").disabled=false;try{await refresh();}catch(_){}}}
async function initialize(){try{if(window.P2K_REAL_OAUTH_READY)await window.P2K_REAL_OAUTH_READY;const session=window.P2K_AUTH?.getSession?.();if(!session){el("authBox").style.display="block";el("loginButton").onclick=()=>window.P2K_AUTH?.login?.();return;}client=window.P2K_TEAM_POINTS_CLIENT;api=window.P2K_API_CLIENT;if(!client?.connect||!api?.processPriority)throw new Error("Required P2K clients are unavailable.");const admin=await client.connect();el("identity").textContent=`Authenticated administrator: ${admin.username||session.username}`;el("tool").classList.remove("hidden");el("refreshButton").onclick=()=>refresh().catch(e=>log(e.message||e,"bad"));el("startButton").onclick=run;el("pauseButton").onclick=()=>{if(controller&&!controller.signal.aborted){controller.abort();log("Pause requested…");}};await refresh();log("Ready. This page can be closed and reopened; the database is the checkpoint.","ok");}catch(error){el("authBox").style.display="block";el("authBox").querySelector("h2").textContent="Administrator access failed";el("authBox").querySelector("p").textContent=error?.message||String(error);el("loginButton").textContent="Retry OAuth login";el("loginButton").onclick=()=>window.P2K_AUTH?.login?.();}}
window.addEventListener("DOMContentLoaded",initialize,{once:true});
})();
</script>
</body>
</html>
