#!/usr/bin/env python3
"""MIAC/MIRA Club Intelligence browser gate, retained and strengthened for POC chain UI."""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json,re
ROOT=Path(__file__).resolve().parents[1];CHROMIUM='/usr/bin/chromium'
def clean_html(name):
 h=(ROOT/name).read_text(encoding='utf-8',errors='ignore');h=re.sub(r'<script\b[^>]*>.*?</script>','',h,flags=re.I|re.S);h=re.sub(r'<meta[^>]+http-equiv=["\']Content-Security-Policy["\'][^>]*>','',h,flags=re.I);return h
BOOT=r'''
const NativeURL=window.URL; function SafeURL(input,base){const b=(!base||String(base)==='about:blank')?'https://p2k.test/ClubIntelligence.html':base;return new NativeURL(input,b)} SafeURL.prototype=NativeURL.prototype;window.URL=SafeURL;
document.documentElement.classList.remove('admin-access-pending');history.replaceState=()=>{};window.P2K_ADMIN_ACCESS_READY=Promise.resolve(true);window.P2K_ADMIN_USERNAME='ximoon';window.__miacWrites=[];
let summary={generation:7,names:6956,player_id_names:311,hard_conflict_names:0,seed_summary:{chains:2,chains_3plus:1,max_chain:3,former_roster_usernames:120,board_only_usernames:20,boards_multi_owner:136,collision_pairs:136},edge_counts:{candidate:1,confirmed:1,rejected:0,conflict:0},chains:[{size:2,members:['oldboard','newboard'],current:['newboard'],member_meta:[{name:'oldboard',status:'former',segments:[['2025-01','2025-05']]},{name:'newboard',status:'current',segments:[['2025-06','2026-08']]}],transitions:[{old:'oldboard',new:'newboard',status:'confirmed',validation_basis:'auto:shared_board',shared_boards:42}]},{size:2,members:['oldmanual','newmanual'],current:['newmanual'],member_meta:[{name:'oldmanual',status:'former'},{name:'newmanual',status:'current'}],transitions:[{old:'oldmanual',new:'newmanual',status:'candidate',validation_basis:'seed',shared_boards:0}]}],edges:[{old_username_key:'oldboard',new_username_key:'newboard',confidence:'Very strong',shared_boards:42,same_joined:true,roster_handover:true,status:'confirmed',reviewed_by:'auto:shared_board',evidence:{sample_boards:['match/1/3']}},{old_username_key:'oldmanual',new_username_key:'newmanual',confidence:'Strong',shared_boards:0,same_joined:true,roster_handover:true,status:'candidate',evidence_source:'seed'}]};
window.fetch=async(url,opt={})=>{const u=String(url);if(u.includes('server/team-points/public/intelligence.php'))return new Response(JSON.stringify({ok:true,data:u.includes('scope=aliases')?summary:{freshness:{coverage:{}},activity_summary:{},telemetry:{acamr:{}},team_depth:[],actions:[]}}),{status:200,headers:{'Content-Type':'application/json'}});return new Response(JSON.stringify({ok:true}),{status:200,headers:{'Content-Type':'application/json'}})};
window.P2K_TEAM_POINTS_CLIENT={endpointRequest:async(url,opt={})=>{if(String(url).includes('miac.php')&&opt.action==='review'){window.__miacWrites.push(opt.body||{});const e=summary.edges.find(x=>x.old_username_key===opt.body.old_username&&x.new_username_key===opt.body.new_username);if(e){e.status=opt.body.decision;e.reviewed_by='ximoon';summary.generation=8;summary.edge_counts.candidate=0;summary.edge_counts.confirmed=2;summary.chains[1].transitions[0].status=opt.body.decision;summary.chains[1].transitions[0].validation_basis='ximoon'}return {ok:true,review:{status:opt.body.decision,generation:8},miac:summary,mira:{current_generation:8,derived_generation:7,stale:true}}}return {ok:true}}};window.confirm=()=>true;window.P2K_EMBEDDED_PAGE={notifyHeight(){}};
'''
def main():
 with sync_playwright() as p:
  b=p.chromium.launch(headless=True,executable_path=CHROMIUM,args=['--no-sandbox','--disable-dev-shm-usage']);page=b.new_page(viewport={'width':1100,'height':800});errors=[];page.on('pageerror',lambda e:errors.append(str(e)));page.set_content(clean_html('ClubIntelligence.html'),wait_until='domcontentloaded');page.add_script_tag(content=BOOT);page.add_script_tag(path=str(ROOT/'assets/js/pages/club-intelligence.js'));page.wait_for_timeout(120);page.locator('[data-tab="aliases"]').click();page.wait_for_timeout(180)
  text=page.locator('#ciContent').inner_text();assert 'Identity chain explorer' in text and 'oldboard' in text and 'newboard' in text;assert 'confirmed' in text and 'auto:shared_board' in text;assert 'Manual confirmation queue' in text and 'oldmanual' in text and 'Confirm' in text
  page.locator('[data-review-old="oldmanual"][data-review-decision="confirmed"]').click();page.wait_for_timeout(220);writes=page.evaluate('()=>window.__miacWrites');assert writes and writes[-1]['decision']=='confirmed';text2=page.locator('#ciContent').inner_text();assert 'Candidates0' in text2.replace(' ','');assert not errors,errors;b.close();print(json.dumps({'chainExplorer':True,'sharedBoardConfirmed':True,'manualReviewPersisted':True,'pageErrors':0},indent=2))
if __name__=='__main__':main()
