#!/usr/bin/env node
"use strict";
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const read = file => fs.readFileSync(path.join(root, file), "utf8");
const assert = (condition, message) => { if (!condition) throw new Error(message); };

const index = read("index.html");
const admin = ["admin-runtime", "logs-controller", "diagnostics-controller", "history-controller", "match-management", "recording-controller"]
  .map(name => read(`assets/js/admin/${name}.js`)).concat(read("assets/js/pages/admin-features.js")).join("\n");
const history = read("assets/js/shared/match-history-ui.js");
const challenge = read("ChallengeListAssistant.html");
const siteCss = read("assets/css/site.css");
const adminCss = read("assets/css/admin-features.css");
const historyCss = read("assets/css/match-history.css");
const siteTabs = read("assets/js/pages/site-tabs.js");
const siteConfig = read("assets/js/site-config.js");
const creationCore = read("assets/js/pages/match-creation-analyzer.js");
const creationCharts = read("assets/js/pages/match-creation-charts.js");
const creationCss = read("assets/css/match-creation-analyzer.css");
const branding = read("config/site-branding.js");
const upcomingHtml = read("AnalyzeMatches.htm");
const upcomingCore = read("assets/js/shared/upcoming-analysis-core.js");
const upcomingCss = read("assets/css/upcoming-matches-analyzer.css");
const challengeJs = read("assets/js/pages/challenge-list-assistant.js");
const challengeCss = read("assets/css/challenge-list-assistant.css");
const recruitJs = read("assets/js/pages/recruit-match.js");
const recruitCss = read("assets/css/recruit-match.css");
const failureUi = read("assets/js/shared/analysis-failure-ui.js");
const failureCss = read("assets/css/analysis-failure-ui.css");
const analyzeMatchJs = read("assets/js/pages/analyze-match.js");
const adminGuard = read("assets/js/shared/admin-page-guard.js");
const tabActivity = read("assets/js/shared/tab-activity.js");
const coordinator = read("assets/js/shared/analysis-coordinator.js");
const apiClient = read("assets/js/shared/api-client.js");
const commonPhp = read("api/_common.php");
const localServer = read("serve_local.py");

assert(index.includes('data-admin-only hidden id="adminOpen"'), "Administration must remain hidden outside admin mode");

assert(index.includes('<title>Promote to King</title>') && index.includes('<h1>Promote to King</h1>'), "Promote to King fallback identity missing");
assert(index.includes('Play together. Improve together. Promote to King.') && index.includes('name="description"'), "Promote to King fallback subtitle missing");
assert(index.includes('config/site-branding.js?v=2.10.6') && index.indexOf('config/site-branding.js') < index.indexOf('assets/js/site-config.js'), "Branding config is not loaded before runtime config");
assert(branding.includes('title: "Promote to King"') && branding.includes('subtitle: "Play together. Improve together. Promote to King."'), "Default branding config is wrong");
assert(branding.includes('clubSlug: "promote-to-king"') && branding.includes('clubUrl: "https://www.chess.com/club/promote-to-king"'), "Configured club identity is missing");
assert(index.includes('id="siteClubLink"') && index.includes('href="https://www.chess.com/club/promote-to-king"'), "Configured club logo link fallback is missing");
for (const key of ["upcoming", "creation", "open", "recruit", "challenges"]) {
  assert(new RegExp(`<button[^>]*data-admin-only[^>]*hidden[^>]*data-key="${key}"|<button[^>]*hidden[^>]*data-admin-only[^>]*data-key="${key}"`).test(index), `${key} tab must be admin-only`);
}
assert(!siteTabs.includes("PRELOAD_KEYS") && !siteTabs.includes("preload"), "Hidden tools must not be preloaded");
assert(siteTabs.includes('siteName || "Promote to King"') && siteConfig.includes('branding.title || "Promote to King"'), "Runtime site title configuration missing");
assert(siteTabs.includes('MAIN_SUBTITLE') && siteTabs.includes('MAIN_LOGO') && siteTabs.includes('applyBranding()'), "Runtime branding application is incomplete");
assert(siteConfig.includes('branding.logoPath') && siteConfig.includes('branding.logoAlt') && siteConfig.includes('branding.clubUrl'), "Runtime logo/club configuration missing");
assert(siteTabs.includes('MAIN_CLUB_URL') && siteTabs.includes('logoLink.href = MAIN_CLUB_URL'), "Configured logo destination is not applied");
assert(siteTabs.includes('key === "recruit"') && siteTabs.includes('url.searchParams.set("lockTeam", "1")'), "Embedded recruitment club lock is missing");
assert(recruitJs.includes('lockTeamSelection') && recruitJs.includes('state.lockTeamSelection && !preferred'), "Recruitment assistant does not enforce the configured club");
assert(recruitJs.includes('recruitment-pool.php') && recruitJs.includes('significantTarget') && recruitJs.includes('lowestOpponentRating'), "Stored-rating recruitment model is incomplete");
assert(recruitCss.includes('.p2k-team-selector[hidden]'), "Locked recruitment team selector is not hidden");
assert(upcomingHtml.includes('>Matches</button>') && upcomingHtml.includes('>Players</button>'), "Upcoming Matches subtabs are missing");
assert(upcomingHtml.includes('id="p2kPlayerSearch"') && upcomingHtml.includes('id="p2kPlayerSort"'), "Upcoming player search/sort controls are missing");
assert(upcomingCore.includes('aggregateRegisteredPlayers') && upcomingCore.includes('matchRuleCategory') && upcomingCore.includes('medianNumber'), "Match-sheet player aggregation is incomplete");
assert(!/api\.chess\.com\/pub\/player/.test(upcomingCore.slice(upcomingCore.indexOf('function aggregateRegisteredPlayers'), upcomingCore.indexOf('function setUpcomingSection'))), "Players subtab must not fetch player profile/stat endpoints");
assert(upcomingCore.includes('p2k-history-expand') || history.includes('p2k-history-expand'), "Recruitment tracker View larger control is missing");
assert(history.includes('Recruitment tracking graph information') && history.includes('P2K_UPCOMING_CHART_MODAL'), "Recruitment tracker information/enlargement integration is missing");
assert(upcomingCss.includes('.p2k-upcoming-tabs') && upcomingCss.includes('.p2k-player-table'), "Upcoming player subtab styling is missing");
assert(challengeJs.includes('highlightBatchId') && challengeJs.includes('p2k-cla-recommendation-new'), "Newest recommendation batch tracking is missing");
assert(challengeCss.includes('.p2k-cla-recommendation-new') && challengeCss.includes('border-left-color: #5fbf6b'), "Newest recommendation green styling is missing");
assert(creationCore.includes('P2K_MATCH_CREATION_CHART_BUCKETS') && creationCore.includes('data-chart-scope="started"'), "Started chart match buckets missing");
assert(creationCharts.includes('data-chart-scope="registration"') && creationCharts.includes('p2k-chart-match-overlay'), "Registration chart overlay missing");
assert(creationCharts.includes('chartBucketRecords') && creationCharts.includes('openChartMatchOverlay'), "Chart match lookup behavior missing");
assert(creationCss.includes('.p2k-chart-match-overlay') && creationCss.includes('.p2k-chart-match-table'), "Chart match overlay styling missing");
assert(creationCharts.includes('aria-label="Close match list">Close</button>'), "Chart match overlay close label/style text missing");
assert(creationCss.includes('rgba(246, 183, 60, .52)') && creationCss.includes('.p2k-chart-match-close:focus-visible') && !creationCss.includes('border-radius: 50%;\n  background: rgba(217, 74, 58, .13)'), "Chart match close button is not aligned with project modals");
assert(index.includes('data-log-tab="match"') && index.includes('data-log-tab="scheduled"'), "Log subtabs missing");
assert(index.indexOf('data-log-tab="match"') < index.indexOf('data-log-tab="scheduled"'), "Match Assistant log tab must come first");
assert(index.includes('id="manualProgressTrack"') && index.includes('id="manualProgressBar"'), "Manual recording progress UI missing");
assert(index.includes('id="managementRecordNow"') && index.includes('id="managementProgressTrack"'), "Match data management recording action missing");
assert(index.includes('id="matchLogRefresh"') && index.includes('id="taskLogRefresh"'), "Log refresh buttons missing");
assert(index.includes('id="managementSearch"') && index.includes('id="managementStatus"') && index.includes('id="managementSort"'), "Management search/filter/sort controls missing");
assert(index.includes('id="managementAddInput"') && index.includes('id="removeFinishedData"'), "Follow/finished cleanup controls missing");
assert(index.includes('>Challenge Assistant</button>'), "Challenge tab rename missing");
assert(challenge.indexOf('data-p2k-tab="recommendation"') < challenge.indexOf('data-p2k-tab="checker"'), "Challenge recommendation must be first");
assert(challenge.includes('data-p2k-tab="recommendation"') && challenge.includes('aria-selected="true"'), "Challenge recommendation must be initially selected");
assert(admin.includes('Array.isArray(data?.entries) ? data.entries : []'), "Scheduled log null-entry guard missing");
assert(admin.includes('refreshActiveLogs()') && admin.includes('selectedValue === "logs"'), "Log access auto-refresh missing");
assert(admin.includes('api/league-match-references/') && admin.includes('api/record-league-match/'), "Optimized two-stage manual recording missing");
assert(admin.includes('data-unfollow=') && admin.includes('mode=finished-data') && admin.includes('data-history='), "Management actions missing");
assert(history.includes('data-p2k-history-index') && history.includes('p2k-history-details-columns'), "Clickable history details missing");
assert(history.includes('Rating') && history.includes('Timeout') && history.includes('Balance'), "Player change detail columns/totals missing");
assert(history.includes('p2k-history-details-slot') && history.includes('ensureDetailsPanel(host)'), "History details are not anchored to their graph host");
assert(history.includes('Copy text') && history.includes('changesPlainText') && history.includes('copyPlainText'), "Plain-text archive change copy is missing");
assert(history.indexOf('p2k-history-details-slot') < history.indexOf('function playerIdentity'), "History overlay slot is not rendered with the graph");
assert(!history.includes('document.body.appendChild(detailsBackdrop)') && !history.includes('document.body.style.overflow = "hidden"'), "Viewport-wide history overlay behavior returned");
assert(index.indexOf('id="snapshotChangesModal"') < index.indexOf('id="historyFeedback"'), "Management change panel is not nested at graph level");
assert(adminCss.includes('.history-dialog > .snapshot-backdrop') && adminCss.includes('min-width: 0'), "Compact graph-local management panel styles missing");
assert(historyCss.includes('position: absolute') && historyCss.includes('width: min(560px, 100%)'), "Graph overlay positioning or compact width missing");
assert(historyCss.includes('.p2k-history-change-table {') && historyCss.includes('font-size: 10px') && historyCss.includes('font-size: 9px'), "Readable desktop/mobile archive table fonts missing");
assert(siteCss.includes('.tool-content {') && siteCss.includes('background: transparent;'), "Original transparent tool frame style changed");
assert(!/(^|[}\s,])(body|html|\.site-shell|\.tool-content|\.tool-frame)\s*[{,]/m.test(adminCss), "Scoped admin CSS overrides the v2.1.2 shell");
assert(!/(cdn\.jsdelivr\.net|raw\.githubusercontent\.com|github\.io)/i.test([index, admin, history, challenge].join("\n")), "Repository/CDN runtime reference found");

assert(upcomingHtml.indexOf('id="p2kAnalyzeButton"') < upcomingHtml.indexOf('class="p2k-upcoming-tabs"'), "Upcoming Analyze button must be above subtabs");
assert(upcomingHtml.includes('id="p2kAnalyzeButton" type="button">Analyze</button>'), "Upcoming action must be named Analyze");
assert(upcomingCore.includes('data-player-sort-field') && upcomingCore.includes('togglePlayerSort') && upcomingCore.includes('openPlayerMatches'), "Interactive Players table sorting or drill-down is missing");
assert(upcomingCore.includes('classicalTimeoutRates') && upcomingCore.includes('chess960TimeoutRates') && upcomingCore.includes('Classical timeout') && upcomingCore.includes('Chess960 timeout'), "Separate Classical/Chess960 timeout reporting is missing");
assert(upcomingCore.includes('function playerTimeoutRate') && !upcomingCore.includes('value > 0 && value <= 1 ? value * 100 : value'), "Upcoming timeout values are still incorrectly rescaled");
assert(!history.includes('value > 0 && value <= 1 ? value * 100 : value') && !admin.includes('value > 0 && value <= 1 ? value * 100 : value'), "Archived timeout values are still incorrectly rescaled");
assert(failureUi.includes('CLUB_ANALYSIS_FAILURE_UI') && failureUi.includes('Copy plain text') && failureUi.includes('API call'), "Shared analysis failure modal is incomplete");
assert(failureCss.includes('.club-analysis-failure-modal') && failureCss.includes('.club-analysis-failure-trigger'), "Shared failure modal styling is missing");
assert(failureUi.includes('visibleModalRegion') && failureUi.includes('positionModalInVisibleViewport') && failureUi.includes('window.parent.addEventListener("scroll"'), "Failure modal is not parent-viewport aware");
assert(failureCss.includes('align-items: flex-start') && failureCss.includes('overscroll-behavior: contain'), "Failure modal visible-area scrolling styles are missing");
assert(creationCore.includes('attachAnalysisFailures(analysisFailureItems()') && creationCore.includes('apiUrl: record.apiUrl'), "Match Creation failed-request drill-down is missing");
assert(upcomingCore.includes('failedDetails') && upcomingCore.includes('Upcoming Matches analysis failures'), "Upcoming failed-request drill-down is missing");
assert(analyzeMatchJs.includes('Open Match Analyzer failure') && analyzeMatchJs.includes('matchApiUrl'), "Open Match Analyzer failure drill-down is missing");
for (const page of [upcomingHtml, read("MatchCreationAnalyzer.htm"), read("AnalyzeMatch.html"), read("AnalyzeMatchModal.html")]) {
  assert(page.includes('analysis-failure-ui.css') && page.includes('analysis-failure-ui.js'), "An analyzer page is missing the shared failure UI assets");
}
assert(siteTabs.includes('authenticatedClubAdmin') && siteTabs.includes('configuredAdminUsernames') && siteTabs.includes('oauthSessionClaimsAdmin'), "Local/OAuth configured-club admin detection is missing");
assert(siteTabs.includes('club-admin-access-ready') && admin.includes('club-admin-access-ready'), "Asynchronous admin access initialization is not wired");

assert(history.includes('Lineup evolution') && history.includes('data-p2k-history-previous') && history.includes('data-p2k-history-next'), "Lineup evolution recording navigation is missing");
assert(index.includes('id="snapshotChangesPrevious"') && index.includes('id="snapshotChangesNext"'), "Management lineup navigation is missing");
assert(upcomingCore.includes('p2kWinProbability = 0') && upcomingCore.includes('minimumEligibilityForfeit'), "Minimum-eligibility 0% win rule is missing");
assert(analyzeMatchJs.includes('configuredClubEligibleCount < minPlayers') && analyzeMatchJs.includes('configuredClubIsSelected ? 0 : 1') && analyzeMatchJs.includes('minimumEligibilityForfeit'), "Direct analysis minimum-eligibility rule is missing");
assert(challenge.includes('data-recommendation-mode="rematch"') && challenge.includes('id="p2kOldestRematch"'), "Rematch recommendation mode controls are missing");
assert(challengeJs.includes('function rematchEntries') && challengeJs.includes('matchesArray(index, "finished")') && challengeJs.includes('sourceMatchId'), "Rematch opportunity scan is incomplete");
assert(index.includes('id="taskLogTaskType"') && index.includes('<th>Run ID</th>'), "Task type filtering or run ID column is missing");
assert(admin.includes('taskType: byId("taskLogTaskType").value') && admin.includes('manual-record-active-matches') && admin.includes('storedMatchIds') && admin.includes('failedMatchIds'), "Manual task identifiers/data are missing");
assert(commonPhp.includes("'runId' => $runId") && commonPhp.includes("'taskType' => $taskType") && commonPhp.includes('task_logs_response'), "PHP task identifiers are missing");
assert(localServer.includes('"runId": run_id') && localServer.includes('task_type_filter'), "Python task identifiers/filter are missing");
assert(tabActivity.includes('p2k-tool-activity') && apiClient.includes('activityAwareOptions'), "Focus-aware acquisition cancellation is missing");
assert(coordinator.includes('!window.P2K_TAB_ACTIVITY.isActive()'), "Inactive synchronized analysis refreshes are not blocked");
assert(!siteTabs.includes('PRELOAD_KEYS') && siteTabs.includes('notifyFrame(previousKey, false)'), "Tab focus lifecycle is incomplete");
assert(siteTabs.includes('if (!oauthEnabled() || window.P2K_AUTH?.enabled !== true) return false;'), "Index admin detection must require the current OAuth flag");
assert(adminGuard.includes('oauthAdminAuthorized') && adminGuard.includes('clubAdminUsernames') && adminGuard.includes('configuredAdminUsernames') && adminGuard.includes('oauthSessionClaimsAdmin'), "Standalone API-primary/OAuth admin verification is incomplete");
assert(adminGuard.includes('P2K_TEAM_POINTS_CLIENT?.connect') && adminGuard.includes('!displayOverride && !simulatedOverride') && adminGuard.includes('api.chess.com/pub/club'), "Standalone admin page gating must use server-authoritative real-admin bootstrap while preserving viewed-identity fallback");
for (const pageName of ["AnalyzeMatches.htm", "MatchCreationAnalyzer.htm", "RecruitMatch.html", "ChallengeListAssistant.html"]) {
  const page = read(pageName);
  assert(page.includes('admin-page-guard.js') && page.includes('admin-access-pending'), `${pageName} is not standalone-admin guarded`);
}
const analyzeMatchPage = read("AnalyzeMatch.html");
assert(!analyzeMatchPage.includes('admin-page-guard.js') && !analyzeMatchPage.includes('admin-access-pending'), "AnalyzeMatch.html must remain public");
const analyzeMatchModal = read("AnalyzeMatchModal.html");
const analysisHost = read("assets/js/shared/detailed-analysis-host.js");
assert(!analyzeMatchModal.includes('admin-page-guard.js') && !analyzeMatchModal.includes('admin-access-pending'), "AnalyzeMatchModal must remain public when launched from Match Assistant");
assert(index.includes('detailed-analysis-host.js') && analysisHost.includes('p2k-open-detailed-analysis'), "Classic shell detailed-analysis host bridge is missing");
assert(read("ui-v2.html").includes('detailed-analysis-host.js'), "UI v2 detailed-analysis host bridge is missing");

console.log("Static UI feature tests passed.");
