#!/usr/bin/env python3
from __future__ import annotations
import hashlib, json, re
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXPECTED_BASE_INDEX_SHA = "fbc0bb721bfbc337c328767062bdf42475860e7399a03ef3a800f6eed28564ca"
GATE_TAG = '<script src="assets/js/pages/ui-version-gate.js?v=2.8.1"></script>\n'

class Parser(HTMLParser):
    def __init__(self): super().__init__(); self.inline=[]; self.ids=[]
    def handle_starttag(self, tag, attrs):
        for name, value in attrs:
            if name.lower().startswith("on"): self.inline.append((tag,name))
            if name == "id" and value: self.ids.append(value)

def check(value, message):
    if not value: raise AssertionError(message)

def main():
    check((ROOT/"VERSION").read_text().strip()=="2.8.1", "VERSION is not 2.8.1")
    index=(ROOT/"index.html").read_text()
    check(index.count(GATE_TAG.strip())==1, "Index gate is missing or duplicated")
    check('data-key="teamInsights"' not in index and 'data-key="tournaments"' not in index, "UI v1 must not expose Team Insights or Tournaments")
    check('data-admin-tab="tournaments"' in index and 'data-admin-panel="tournaments"' in index, "Tournament management administration tab is missing")
    check('value="match-update"' in index and 'value="database-update"' in index and 'value="tournaments-update"' in index, "Scheduled-task type filters are incomplete")
    gate=(ROOT/"assets/js/pages/ui-version-gate.js").read_text()
    check('selected !== "v2"' in gate and 'page === "ui-v2.html"' in gate, "Strict v2 selector is incomplete")
    dashboard=(ROOT/"ui-v2.html").read_text()
    parser=Parser(); parser.feed(dashboard)
    check(not parser.inline, f"Inline event handlers found: {parser.inline}")
    check(len(parser.ids)==len(set(parser.ids)), "Duplicate dashboard IDs found")
    check("dashboard-v2.css?v=2.8.1" in dashboard and "dashboard-v2.js?v=2.8.1" in dashboard, "Dashboard assets are missing")
    check('data-public-page="insights"' in dashboard and 'data-public-page="hall"' in dashboard and 'data-public-page="tournaments"' not in dashboard, "UI v2 public page hierarchy is wrong")
    check('id="teamInsightsPage"' in dashboard and 'id="hallOfFamePage"' in dashboard and 'id="tournamentsFrame"' in dashboard, "Insights/Hall integrated pages are missing")
    for subtab in ('team','members','matches','opponents'):
        check(f'data-insights-subtab="{subtab}"' in dashboard, f"Insights subtab missing: {subtab}")
    check(dashboard.count('data-insights-subtab=') == 4 and dashboard.count('data-insights-subtab="members"') == 1, "Insights subtabs are duplicated or incomplete")
    check('data-insights-subtab="members"' in dashboard and '>Members</button>' in dashboard and '>Matches</button>' in dashboard and '>Opponents</button>' in dashboard, "Insights subtabs are missing")
    check('data-hall-subtab="daily"' in dashboard and 'data-hall-subtab="live"' in dashboard and 'data-hall-subtab="tournaments"' in dashboard, "Hall of Fame subtabs are incomplete")
    check('data-hall-subtab="live"' in dashboard and '>Live ranks</button>' in dashboard and 'id="liveRanksNativeGrid"' in dashboard and 'id="liveRanksFrame"' not in dashboard, "Native Live ranks subtab is missing")
    check("simulated-oauth.js?v=2.8.1" in dashboard and "api-client.js?v=2.8.1" in dashboard, "Existing auth/API integration is missing")
    check('id="p2kAuthHost"' in dashboard, "Dashboard authentication control host is missing")
    dashboard_js=(ROOT/"assets/js/pages/dashboard-v2.js").read_text()
    rank_ladder_js=(ROOT/"assets/js/shared/rank-ladder.js").read_text()
    finder_js=(ROOT/"assets/js/pages/find-match.js").read_text()
    check('writeNavigationState' in dashboard_js and 'window.history[method]' in dashboard_js and 'popstate' in dashboard_js, "URL-backed page persistence is missing")
    check('url.searchParams.set("page", state.publicPage)' in dashboard_js and 'url.searchParams.set("hall", state.hallSubtab)' in dashboard_js, "Page/subtab URL state is incomplete")
    check('requestedPage === "team-insights"' in dashboard_js and 'requestedPage === "tournaments"' in dashboard_js, "Legacy navigation aliases are missing")
    check('id="personalJoinDate"' in dashboard and 'memberRecord(state.membersPayload' in dashboard_js and 'Joined P2K' in dashboard_js, "Club join-date display is missing")
    check('p2k-dashboard-recommendations-progress' in dashboard_js and 'p2k-dashboard-recommendations-progress' in finder_js, "Granular Match Assistant loading progress bridge is missing")
    check('loadingTarget' not in dashboard_js and 'dashboardLoadProgress' not in dashboard, "The removed top dashboard loader is still present")
    check('<h3 id="teamStatsTitle">Promote to King</h3>' in dashboard and '<h3 id="recommendationsTitle">Recommended matches</h3>' in dashboard, "Dashboard panel titles are not unified")
    check('Match Assistant results' not in dashboard and 'Five recommended matches' not in dashboard and 'same order as the Match Assistant' not in dashboard_js, "Recommendation copy was not simplified")
    check('Search collapses the ladder' not in dashboard and '>Clear</button>' in dashboard and 'Show all ranks' not in dashboard, "Hall search/rank controls were not simplified")
    check('id="hallRankedMembers"' in dashboard and 'hallTotalPoints' not in dashboard and 'current members across 16 ranks' not in dashboard_js, "Hall ranked-member summary is incorrect")
    check('Classic UI' not in dashboard and 'classicUiLink' not in dashboard_js, "Public Classic UI link was not removed")
    check('scrollIntoView({ behavior: "smooth", block: "start" })' in dashboard_js, "Opened Hall rank does not align to the top")
    check('data-p2k-info-message' in dashboard and dashboard.count('p2k-info-button p2k-info-mark') >= 5, "Shared blue metric information controls are missing")
    check('dashboardRecommendations' in dashboard_js and 'p2k-dashboard-recommendations' in dashboard_js, "Dashboard Match Assistant bridge is missing")
    check(dashboard_js.count('document.createElement("iframe")') == 1, "Dashboard creates more than one Match Assistant iframe")
    check('p2k-dashboard-full-assistant-ready' in dashboard_js and 'p2k-dashboard-full-assistant-ready' in finder_js, "Prepared-assistant reveal handshake is missing")
    check('state.assistantFrame = frame' in dashboard_js and 'state.assistantFullReady = false' in dashboard_js, "Recommendation frame is not reused as the full assistant")
    check('postDashboardRecommendations(sortedMatches' in finder_js, "Match Assistant does not publish its sorted top results")
    check('displayRatingRange(item.ratingRange)' in dashboard_js and 'item.rules' in dashboard_js and '"Open rating"' in dashboard_js, "Compact rating/rules recommendation tags are missing")

    check('id="dashboardLoadProgress"' not in dashboard and 'id="dashboardLoadBar"' not in dashboard, "The top dashboard loading bar was not removed")
    check('id="personalTeamPoints"' in dashboard and 'id="personalRankImage"' in dashboard, "Player points/rank display is missing")
    check('id="personalModeToggle"' in dashboard and 'data-player-mode="daily"' in dashboard and 'data-player-mode="live"' in dashboard, "Daily/Live player-card toggle is missing")
    for metric_id in ('personalLiveBestScore','personalLiveTotalWins','personalLiveMaxWins','personalLiveBestStreak'):
        check(f'id="{metric_id}"' in dashboard, f"Live player metric is missing: {metric_id}")
    check('action=live-player' in dashboard_js and 'renderLivePersonalCard' in dashboard_js, "Live player-card data integration is missing")
    check('id="personalWins"' in dashboard and 'id="personalDraws"' in dashboard and 'id="personalLosses"' in dashboard, "Team Points W/D/L counters are missing")
    check('personalDailyRating' not in dashboard and 'personalChess960Rating' not in dashboard, "Personal ratings were not removed")
    check('id="personalMatchAssistantLink"' not in dashboard, "Personal suitable-match link was not removed")
    check('id="teamRegisteredBoards"' in dashboard and 'id="teamOngoingBoards"' in dashboard and 'id="teamFinishedBoards"' in dashboard, "Match board/game totals are missing")
    check('data-match-list="registered"' in dashboard and 'data-match-list="ongoing"' in dashboard and 'data-match-list="finished"' in dashboard, "Match list View controls are missing")
    check('id="dashboardMatchListModal"' in dashboard and 'openDashboardMatchList' in dashboard_js, "Dashboard match list modal is missing")
    check('Overall team statistics' not in dashboard, "Removed team statistics heading is still present")
    check('setText("personalStatsTitle", loggedIn ? state.session.username : "Member")' in dashboard_js, "Nickname is not used as the personal heading")
    for metric_id in ("teamMembers", "teamActiveMatches", "teamClubPoints", "teamOpenRegistrations", "teamFinishedMatches", "teamLineupReadinessValue", "teamRegistrationTargetsValue", "teamStartingSoon", "teamPriorityCalls"):
        check(f'id="{metric_id}"' in dashboard, f"Dashboard team indicator missing: {metric_id}")
    check('clubProfileAPI}/members' in dashboard_js and 'P2K_TEAM_POINTS_CLIENT?.publicRequest?.("team")' in dashboard_js, "Live member/Team Points dashboard sources are missing")
    check('publicRequest?.("player"' in dashboard_js and 'rankForPoints' in dashboard_js, "Player Team Points/rank integration is missing")
    check('id="personalCurrentGames"' in dashboard and 'id="personalRegisteredMatches"' in dashboard and 'id="personalPlayedGames"' in dashboard, "Player activity metrics are missing")
    check('id="explorePlayerGames"' in dashboard and 'id="playerGamesModal"' in dashboard and 'openPlayerGames' in dashboard_js, "Player games explorer is missing")
    check('/player/${encodeURIComponent(normalized)}/matches' in dashboard_js, "Player matches endpoint integration is missing")
    check('statusLabel = !available ? "—"' in dashboard_js and '`${Math.round(bounded)}%`' not in dashboard_js, "Gauge percentage labels were not removed")
    css=(ROOT/"assets/css/dashboard-v2.css").read_text()
    check('.dashboard-recommendation-line { display: flex' in css and 'flex-wrap: nowrap' in css and 'white-space: nowrap' in css, "Desktop recommendation single-line layout is missing")
    check('.dashboard-modal-backdrop[hidden] { display: none !important; }' in css, "Dashboard modal hidden override is missing")
    team_points=(ROOT/"TeamPointsAdmin.html").read_text()
    check('tpApiUrl' not in team_points and 'tpAdminToken' not in team_points, "Team Points still asks for an API path or secret")
    client=(ROOT/"assets/js/shared/team-points-client.js").read_text()
    check('HttpOnly same-origin session + CSRF' in client and 'teamPointsSessionEndpoint' in client, "Automatic secured Team Points connection is missing")
    check('CONNECT_TIMEOUT_MS = 35000' in client and 'fetchWithTimeout' in client, "Bounded Team Points browser requests are missing")
    database_php=(ROOT/"server/team-points/src/Database.php").read_text()
    check('PDO::ATTR_TIMEOUT => $connectTimeout' in database_php and 'innodb_lock_wait_timeout' in database_php, "MariaDB connection/lock timeouts are missing")
    core_schema=(ROOT/"server/team-points/sql/core-schema.sql").read_text()
    analytics_schema=(ROOT/"server/team-points/sql/analytics-schema.sql").read_text()
    schema_sql=core_schema+"\n"+analytics_schema
    check('CREATE TABLE IF NOT EXISTS p2k_tp_boards' in core_schema and 'CREATE VIEW p2k_tp_board_states' in core_schema and 'GROUP BY club_slug, username_key, board_url' not in core_schema, "Compact board storage / compatibility view is missing")
    repository_php=(ROOT/"server/team-points/src/Repository.php").read_text()
    check('backfillBoardStatesBatch' in repository_php, "Incremental board-state backfill is missing")
    check('CREATE VIEW p2k_tp_match_summaries' in core_schema and 'CREATE TABLE IF NOT EXISTS p2k_tp_club_totals' in analytics_schema and 'p2k_core_schema_version' in core_schema, "v2.8 Core/Analytics compatibility surfaces are missing")
    check('finalizeMatchSummaryIfComplete' in repository_php and 'backfillMatchSummariesBatch' in repository_php and 'cache_mode' in repository_php, "Immutable match-summary cache is incomplete")
    check('CREATE TABLE IF NOT EXISTS p2k_tp_games' in core_schema and 'UNIQUE KEY uq_tp_game_board_seq' in core_schema and 'verified_at' in core_schema, "Compact canonical game identity/verification is missing")
    worker_php=(ROOT/"server/team-points/src/Worker.php").read_text()
    fast_audit=(ROOT/"server/team-points/public/fast-former-member-audit.php").read_text()
    full_audit=(ROOT/"server/team-points/public/consistency-repair.php").read_text()
    check('finalizeMatchSummaryAuthoritatively' in worker_php and "$status !== 'finished'" in repository_php, "Authoritative finished-status guard is missing")
    check('current_member=0' in fast_audit and 'Apply selected fixes' in fast_audit or '3. Apply selected fixes' in fast_audit and 'rollback' in fast_audit.lower(), "Fast former-member audit is incomplete")
    check('Audit database' in full_audit and 'Apply selected repairs' in full_audit and 'rollback' in full_audit.lower(), "Complete consistency repair page is incomplete")
    check('Consistency &amp; repair' in team_points and 'database-repair.php' in team_points and 'Fast arithmetic audit' in (ROOT/'server/team-points/public/database-repair.php').read_text(), "Resumable Team Points repair tool is not exposed in Administration")
    check('id="dashboardPublicTabs"' in dashboard and 'data-public-page="dashboard"' in dashboard and 'data-public-page="hall"' in dashboard, "Full-page public navigation tabs are missing")
    check('Suggested additions' not in dashboard and 'More useful public modules' not in dashboard, "Legacy suggested-additions card is still present")
    check('focusCurrentMember: true' in dashboard_js and 'loadHall({ member })' in dashboard_js and 'tr.is-highlighted' in rank_ladder_js, "Player Hall of Fame deep-opening/highlight is missing")
    check((ROOT/"server/team-points/public/session.php").is_file() and (ROOT/"server/team-points/public/public.php").is_file(), "Team Points session/public endpoints are missing")
    ranks=sorted((ROOT/"assets/images/ranks").glob("*.png"))
    check(len(ranks)==32, f"Expected 32 rank PNGs, found {len(ranks)}")
    check(len([p for p in ranks if "_points" not in p.name])==16, "Expected 16 frameless ranks")
    check(len([p for p in ranks if "_points" in p.name])==16, "Expected 16 framed point ranks")
    thumbnails=sorted((ROOT/"assets/images/ranks/thumbs").rglob("*.webp"))
    check(len(thumbnails)==64, f"Expected 64 optimized rank thumbnails, found {len(thumbnails)}")
    check(all(p.stat().st_size < 500_000 for p in thumbnails), "A rank thumbnail is unexpectedly large")
    check('dashboard-tab-icon' in dashboard and dashboard.count('dashboard-tab-icon')==4 and 'data-public-page="administration"' in dashboard, "UI v2 must expose Dashboard, Insights, Hall of Fame and the hidden administrator tab")
    check('rankThumbnailAsset' in dashboard_js and 'setRankImage' in dashboard_js, "Optimized rank-image selection is missing")
    check('window.scrollTo({ top: 0' not in dashboard_js, "Public tabs still force a scroll jump")
    check('id="hallOfFamePage"' in dashboard and 'id="hallMemberSearch"' in dashboard and 'id="hallRankGrid"' in dashboard, "Hall of Fame full-page view/search is missing")
    check('publicRequest("hall"' in dashboard_js and 'dashboard-hall-rank-card' in dashboard_js, "Live Hall of Fame integration is missing")
    check('framed_image' in dashboard_js and 'category_position' in dashboard_js and 'team_position' in dashboard_js, "Hall member standings/rank artwork are incomplete")
    check('id="dashboardMatchAssistant"' in dashboard and 'openMatchAssistant' in dashboard_js, "In-place Match Assistant is missing")
    check('personalLastOnline' not in dashboard, "Last-online dashboard metric was not removed")
    site_config=(ROOT/"assets/js/site-config.js").read_text()
    check('version: "2.8.1"' in site_config and 'schemaVersion: 5' in site_config, "Runtime package metadata is stale")
    check('RUNTIME_VERSION = "2.8.1"' in (ROOT/"assets/js/shared/api-client.js").read_text(), "API client runtime version is stale")
    admin_js="\n".join(path.read_text() for path in (ROOT/"assets/js/admin").glob("*.js"))+(ROOT/"assets/js/pages/admin-features.js").read_text()
    check('loaded: false' in admin_js and 'Team Points scheduler' in admin_js and 'cron_state' in admin_js, "Expanded diagnostics are missing")
    check('ClubTools/2.8.1' in (ROOT/"api/_common.php").read_text() and 'ClubToolsLocal/2.8.1' in (ROOT/"serve_local.py").read_text(), "Server runtime versions are stale")
    check('id="dashboardAdminToggleHost"' in dashboard.split('id="p2kAuthHost"')[0] and 'id="dashboardViewBar"' not in dashboard, "Admin toggle host must remain empty until local/OAuth authorization is resolved")
    check('adminFlagEnabled' in dashboard_js and 'oauthSessionClaimsAdmin' in dashboard_js and 'configuredAdminUsernames' in dashboard_js and 'ensureAdminInterface' in dashboard_js, "Admin toggle is not local/OAuth gated")
    verify_block=dashboard_js[dashboard_js.index('async function verifyAdmin'):dashboard_js.index('function adminPanelMarkup')]
    check('P2K_TEAM_POINTS_CLIENT' not in verify_block and 'clubProfileAPI' in verify_block and 'apiAuthoritative ? apiAllowed : fallbackAllowed' in verify_block, "Dashboard admin admission must use public API primary without DB access")
    check('rank?.maximum !== null' in dashboard_js and 'no upper boundary' in dashboard_js, "Diamond King upper-bound handling is incorrect")
    check('{ minimum: 10, key: "pawn"' in dashboard_js and 'key: "unranked"' in dashboard_js, "Pawn must start at 10 Team Points")
    check('assets/css/info-popover.css?v=2.8.1' in dashboard and 'assets/js/shared/info-popover.js?v=2.8.1' in dashboard, "UI v2 shared blue information popover assets are missing")
    check('dashboard-recommendation-info-button p2k-info-button' in dashboard_js and 'dashboard-recommendation-popover p2k-info-popover' in dashboard_js, "Dashboard recommendation info tips do not use the shared UI v1 style")
    check('.dashboard-primary-grid { margin-bottom: 14px; }' in css, "Gap below the player/team panels is missing")
    detailed_host=(ROOT/"assets/js/shared/detailed-analysis-host.js").read_text()
    check('p2k-open-detailed-analysis' in detailed_host and 'p2kShellDetailedAnalysisModal' in detailed_host, "Parent-window detailed analysis host is missing")
    check('window.parent.postMessage({ type: "p2k-open-detailed-analysis"' in finder_js, "Embedded Match Assistant does not delegate detailed analysis to the visible shell")
    check('admin-page-guard.js' not in (ROOT/"AnalyzeMatch.html").read_text(), "Open Match Analyzer is incorrectly admin-guarded")
    check('admin-page-guard.js' not in (ROOT/"AnalyzeMatchModal.html").read_text(), "Detailed analysis modal is incorrectly admin-guarded")
    for removed_text in ("Club home", "Public dashboard", "Personal activity, overall club indicators", "Personalized member view", "Dashboard UI v2", "Signed in as"):
        check(removed_text not in dashboard, f"Removed dashboard text is still visible: {removed_text}")
    check('dashboardMatchAssistantHost' in dashboard and 'prepareEmbeddedMatchAssistant' in dashboard_js and 'frame.dataset.username = username' in dashboard_js, "Cached full-width Match Assistant reuse is incomplete")
    check('tpPrioritizeDiscovery' in team_points and 'prioritize_discovery' in (ROOT/"assets/js/pages/team-points-admin.js").read_text(), "Priority member discovery control is missing")
    check('queuePriorityDiscovery' in repository_php and "item_key LIKE 'priority-discovery:%'" in repository_php, "Priority discovery queue implementation is missing")
    check("win=5×boards; draw=2×boards; loss=0" in repository_php and "FROM p2k_tp_participations p" in repository_php and "resolveDataClubSlug" in repository_php, "Backward-compatible DB finished-match scoring is incomplete")
    tournament_service=(ROOT/"server/tournaments/src/TournamentService.php").read_text()
    tournament_admin=(ROOT/"TournamentManagement.html").read_text()
    tournament_cron=(ROOT/"server/tournaments/public/cron.php").read_text()
    team_cron=(ROOT/"server/team-points/public/cron.php").read_text()
    shared_log=(ROOT/"server/shared/ScheduledTaskLogger.php").read_text()
    check('placementMap' in tournament_admin and 'place>=4' in tournament_admin and 'fair_play' in tournament_admin and 'abuse' in tournament_admin, "Tournament medalist validation/ranking logic is missing")
    tournament_endpoint=(ROOT/"server/tournaments/public/tournaments.php").read_text()
    check('reinitializeArchive' in tournament_service and 'archive-' in tournament_service and 'backups' in tournament_service, "Tournament archive backup/reinitialization is missing")
    check("mode:'reinitialize'" in tournament_admin and "Type REINITIALIZE" in tournament_admin and "$('podiums').checked=true" in tournament_admin and "$('accounts').checked=true" in tournament_admin, "Full tournament/podium rebuild UI is incomplete")
    check("'reinitialize'" in tournament_endpoint and 'tournament-full-reinitialize' in tournament_endpoint, "Tournament reinitialize endpoint/logging is missing")
    check((ROOT/"data/tournaments/backups/.gitkeep").is_file(), "Tournament backup directory placeholder is missing")
    check("tournaments-update" in tournament_cron and "database-update" in team_cron and "ScheduledTaskLogger::append" in tournament_cron and "ScheduledTaskLogger::append" in team_cron, "Unified CRON task logging is missing")
    check((ROOT/"server/team-points/src/RetryableException.php").is_file(), "RetryableException autoload hotfix is missing")
    check('updatedItems' in shared_log and 'excludedItems' in shared_log, "Shared scheduled-task log schema is incomplete")

    manifest=json.loads((ROOT/"site-manifest.json").read_text())
    check(manifest.get("version")=="2.8.1" and manifest.get("releaseVersion")=="2.8.1", "Manifest version is wrong")
    check(manifest.get("uiVariants",{}).get("default")=="v1", "Manifest default UI is not v1")
    check(len(manifest.get("rankAssets",[]))==32, "Manifest rank list is incomplete")
    print("v2.8.1 dashboard progress, Hall of Fame and typography tests passed.")

if __name__ == "__main__": main()
