const fs=require('fs'),vm=require('vm');global.window=global;vm.runInThisContext(fs.readFileSync(__dirname+'/../assets/js/shared/recruitment-lineup-core.js','utf8'));
const uut=global.P2K_RECRUITMENT_LINEUP_CORE;
const LR=.65,FR=1200,FC=50;
const numeric=(v,f)=>v===undefined||v===null||v===''?f:(Number.isFinite(Number(v))?Number(v):f);
const bounds=m=>({minimum:Math.max(0,numeric(m?.settings?.min_rating,0)),maximum:(()=>{const n=numeric(m?.settings?.max_rating,Infinity);return n>0?n:Infinity})()});
const ratings=(t,b)=>(Array.isArray(t?.players)?t.players:[]).map(p=>Number(p?.rating)).filter(r=>Number.isFinite(r)&&r>=b.minimum&&r<=b.maximum).sort((a,b)=>b-a);
const minP=m=>{const n=Number(m?.settings?.min_team_players);return Number.isFinite(n)&&n>0?Math.floor(n):0};const maxP=m=>{const n=Number(m?.settings?.max_team_players);return Number.isFinite(n)&&n>0?Math.floor(n):Infinity};const elo=(a,b)=>1/(1+Math.pow(10,(b-a)/400));
function probs(scores){let d=[1];for(const s of scores)for(let t=0;t<4;t++){const n=new Array(d.length+1).fill(0);for(let i=0;i<d.length;i++){n[i]+=d[i]*(1-s);n[i+1]+=d[i]*s}d=n}const th=scores.length*2;let p=0,o=0,dr=0;d.forEach((x,u)=>u>th?p+=x:u<th?o+=x:dr+=x);return{p2kWin:p,opponentWin:o,draw:dr}}
const adjust=r=>{const n=Number(r);if(!Number.isFinite(n))return 0;if(n>=FR)return n;const s=FR-n;return n-25-s*.25};
function cmp(pR,oR,max){const p=Number.isFinite(max)?pR.slice(0,max):[...pR],o=Number.isFinite(max)?oR.slice(0,max):[...oR],bc=Math.min(p.length,o.length),scores=[];let pa=0,oa=0,t=0,rd=0;for(let i=0;i<bc;i++){const d=p[i]-o[i];rd+=adjust(p[i])-adjust(o[i]);if(d>0)pa++;else if(d<0)oa++;else t++;scores.push(elo(p[i],o[i]))}const out=scores.length?probs(scores):{p2kWin:0,opponentWin:0,draw:1};return{boardCount:bc,p2kAdvantageBoards:pa,opponentAdvantageBoards:oa,tiedBoards:t,netBoardAdvantage:pa-oa,reliabilityAdjustedAverageDifference:bc?rd/bc:0,p2kWinProbability:out.p2kWin,opponentWinProbability:out.opponentWin}}
function reached(c,t,l){if(!c||c.boardCount<t)return false;if(l){const rn=Math.min(t,Math.max(2,Math.ceil(t*.20))),ra=Math.max(rn,Math.ceil(t*.60));return c.netBoardAdvantage>=rn&&c.p2kAdvantageBoards>=ra&&c.p2kWinProbability>=LR}return c.p2kWinProbability>=c.opponentWinProbability}
function floor(o,t,min,max){if(!o.length)return Math.min(max,Math.max(min,FR));const count=Math.max(1,Math.min(t,o.length)),top=Math.max(1,Math.ceil(count/2)),boundary=Number(o[top-1])||FR,preferred=Math.max(FR,boundary+FC);return Math.min(max,Math.max(min,Math.ceil(preferred/25)*25))}
function cand(min,max,p,l){const out=[],add=(a,b)=>{for(let r=a;r<=b;r+=25)out.push(r)};if(l)add(min,max);else{add(p,max);if(p>min)add(min,p-25)}return out}
function ref(match,p2k,opp,isLeague){if(!p2k||!opp)return null;const b=bounds(match),max=maxP(match),min=minP(match),pr=ratings(p2k,b),or=ratings(opp,b),mandatory=Math.max(0,min),cm=Number.isFinite(max)?Math.min(max,mandatory):mandatory,missing=Math.max(0,cm-pr.length),oc=Number.isFinite(max)?Math.min(max,or.length):or.length,target=isLeague?(Number.isFinite(max)?Math.min(max,Math.max(cm,oc)):Math.max(cm,oc)):oc;let co=[...or];if(isLeague&&or.length<target){const cur=[...or].sort((a,b)=>b-a),fallback=Math.max(b.minimum,Math.min(Number.isFinite(b.maximum)?b.maximum:FR,FR)),avg=cur.length?cur.reduce((a,b)=>a+b,0)/cur.length:fallback,med=cur.length?cur[Math.floor(cur.length/2)]:fallback,assumed=Math.max(b.minimum,Math.min(Number.isFinite(b.maximum)?b.maximum:3000,Math.ceil(Math.max(avg,med)/25)*25));co=[...cur,...Array.from({length:Math.max(0,target-cur.length)},()=>assumed)].sort((a,b)=>b-a)}const base=Math.max(0,target-pr.length,missing),current=cmp(pr,co,max);if(p2k?.locked===true)return{count:0,baseline:base,ready:true,locked:true};if(target===0&&missing===0)return{count:0,baseline:base,ready:true};if(missing===0&&pr.length>=target&&reached(current,target,isLeague))return{count:0,baseline:base,ready:true};const top=Math.max(1800,pr[0]||0,co[0]||0),maxC=Number.isFinite(b.maximum)?Math.min(3000,Math.floor(b.maximum/25)*25):Math.min(3000,Math.ceil((top+400)/25)*25),minC=Math.min(maxC,Math.max(100,Math.ceil(b.minimum/25)*25)),maxR=Math.max(base,Math.min(12,Math.max(Number.isFinite(max)?Math.min(max,8):6,1))),pref=isLeague?minC:floor(co,target,minC,maxC),cs=cand(minC,maxC,pref,isLeague);let sol=null;for(let count=Math.max(1,base);count<=maxR&&!sol;count++)for(const rating of cs){const projected=[...pr,...Array.from({length:count},()=>rating)].sort((a,b)=>b-a),c=cmp(projected,co,max);if(projected.length>=cm&&projected.length>=target&&(target===0||reached(c,target,isLeague))){sol={count,rating};break}}const mc=sol?.count??Math.max(1,base),sm=Math.max(2,Math.ceil(mc*.25));return{count:mc+sm,modelCount:mc,safetyMargin:sm,baseline:base,ready:false,feasible:Boolean(sol)}}
let seed=0x12345678;const rnd=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/2**32};const ri=(a,b)=>Math.floor(rnd()*(b-a+1))+a;
for(let n=0;n<200;n++){const min=ri(0,6)*100,max=min+ri(4,18)*100,minTeam=ri(0,8),maxTeam=ri(Math.max(1,minTeam),14),mkTeam=()=>({locked:false,players:Array.from({length:ri(0,14)},()=>({rating:ri(Math.max(100,min||100),Math.max(min+100,Math.min(3000,max)))}))}),p=mkTeam(),o=mkTeam(),m={settings:{min_rating:min,max_rating:max,min_team_players:minTeam,max_team_players:maxTeam}},league=n%2===0;if(n%37===0)p.locked=true;const a=ref(m,p,o,league),b=uut.recruitmentMetrics({match:m,p2kTeam:p,opponentTeam:o,isLeague:league});if(JSON.stringify(a)!==JSON.stringify(b)){console.error('Mismatch',n,a,b,m,p,o);process.exit(1)}}
console.log('PASS 200 recruitment parity cases');
