<?php
declare(strict_types=1);
require_once dirname(__DIR__,3).'/api/_common.php';
require_once dirname(__DIR__).'/src/bootstrap.php';
use P2K\Tournaments\BrowseIndex;
// Medalist exclusions are materialized in BrowseIndex; legacy rule: $excluded and !isset($excluded[strtolower($name)]).

try {
    if (strtoupper((string)($_SERVER['REQUEST_METHOD'] ?? 'GET')) !== 'GET') api_error(405,'METHOD_NOT_ALLOWED','GET required.');
    $view=strtolower(trim((string)($_GET['view']??'ranking')));if(!in_array($view,['summary','ranking','tournaments','player','medals','medalist_names'],true))$view='ranking';
    $indexer=new BrowseIndex();$etag=$indexer->requestEtag($_GET);header('Content-Type: application/json; charset=utf-8');header('X-Content-Type-Options: nosniff');header('Cache-Control: public, max-age=120, stale-while-revalidate=600');header('ETag: '.$etag);
    // Fast 304: archive signature + query are enough; do not rebuild/load ranking.
    if(trim((string)($_SERVER['HTTP_IF_NONE_MATCH']??''))===$etag){http_response_code(304);exit;}
    $index=$indexer->index();$ranking=$index['ranking']??[];$tournaments=$index['tournaments']??[];$summary=$index['summary']??[];$years=$index['years']??[];$payload=['ok'=>true,'view'=>$view,'generated_at'=>$index['generatedAt']??null,'recovery_source'=>$index['recoverySource']??null,'index_signature'=>$indexer->signature()];
    if($view==='summary')$payload+=['summary'=>$summary,'years'=>$years];
    elseif($view==='medalist_names')$payload['usernames']=array_values(array_map(static fn($r)=>(string)$r['name'],$ranking));
    elseif($view==='medals'){$wanted=array_slice(array_values(array_unique(array_filter(array_map(static fn($x)=>strtolower(trim($x)),explode(',',(string)($_GET['usernames']??'')))))),0,100);$map=[];$rm=$index['ranking_map']??[];foreach($wanted as $k)$map[$k]=$rm[$k]??['name'=>$k,'gold'=>0,'silver'=>0,'bronze'=>0,'podiums'=>0,'tournamentCount'=>0,'tournaments'=>[]];$payload['medals']=$map;}
    elseif($view==='player'){$u=strtolower(trim((string)($_GET['username']??'')));$player=$index['players'][$u]??['name'=>(string)($_GET['username']??''),'gold'=>0,'silver'=>0,'bronze'=>0,'podiums'=>0,'tournamentCount'=>0,'participationCount'=>0,'tournaments'=>[]];$payload['player']=$player;$played=[];foreach(array_unique($player['participations']??[]) as $i)if(isset($tournaments[(int)$i]))$played[]=$tournaments[(int)$i];$payload['participations']=$played;}
    else {
        $page=max(1,(int)($_GET['page']??1));$pageSize=max(10,min(50,(int)($_GET['page_size']??25)));$search=strtolower(trim((string)($_GET['search']??'')));
        if($view==='ranking'){$rows=$ranking;if($search!=='')$rows=array_values(array_filter($rows,static fn($r)=>str_contains(strtolower((string)$r['name']),$search)));$sort=(string)($_GET['sort']??'rank');$dir=strtolower((string)($_GET['direction']??'asc'))==='desc'?-1:1;$allowed=['rank','name','gold','silver','bronze','podiums','tournamentCount'];if(!in_array($sort,$allowed,true))$sort='rank';usort($rows,static function($a,$b)use($sort,$dir){$av=$a[$sort]??0;$bv=$b[$sort]??0;$cmp=is_numeric($av)&&is_numeric($bv)?($av<=>$bv):strcasecmp((string)$av,(string)$bv);return $dir*$cmp;});}
        else {$rows=$tournaments;$year=trim((string)($_GET['year']??''));$type=strtolower(trim((string)($_GET['type']??'')));$player=strtolower(trim((string)($_GET['player']??'')));$names=static fn($v):array=>array_values(array_filter(array_map(static fn($x):string=>trim((string)(is_array($x)?($x['username']??$x['name']??''):$x)),is_array($v)?$v:[])));$rows=array_values(array_filter($rows,function($t)use($search,$year,$type,$player,$names){$hay=strtolower((string)($t['name']??'').' '.(string)($t['slug']??'').' '.implode(' ',$names($t['players']??$t['participants']??$t['members']??[])).' '.implode(' ',$names($t['podium']['gold']??[])).' '.implode(' ',$names($t['podium']['silver']??[])).' '.implode(' ',$names($t['podium']['bronze']??[])));if($search!==''&&!str_contains($hay,$search))return false;if($year!==''&&!str_contains((string)($t['period']??$t['periodSort']??''),$year))return false;if($type!==''&&$type!=='all'&&strtolower((string)($t['type']??''))!==$type)return false;if($player!==''){foreach(['players','participants','members'] as $field)foreach($names($t[$field]??[]) as $n)if(strtolower($n)===$player)return true;foreach(['gold','silver','bronze'] as $m)foreach($names($t['podium'][$m]??[]) as $n)if(strtolower($n)===$player)return true;return false;}return true;}));$sort=(string)($_GET['sort']??'periodSort');$dir=strtolower((string)($_GET['direction']??'desc'))==='asc'?1:-1;usort($rows,static function($a,$b)use($sort,$dir,$names){if(in_array($sort,['gold','silver','bronze'],true)){$av=count($names($a['podium'][$sort]??[]));$bv=count($names($b['podium'][$sort]??[]));return $dir*($av<=>$bv);} $av=(string)($a[$sort]??$a['periodSort']??'');$bv=(string)($b[$sort]??$b['periodSort']??'');return $dir*strnatcasecmp($av,$bv);});}
        $total=count($rows);$pages=max(1,(int)ceil($total/$pageSize));$page=min($page,$pages);$payload+=['rows'=>array_slice($rows,($page-1)*$pageSize,$pageSize),'pagination'=>['page'=>$page,'page_size'=>$pageSize,'total_rows'=>$total,'total_pages'=>$pages],'summary'=>$summary,'years'=>$years];
    }
    echo json_encode($payload,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);
} catch(Throwable $e){error_log('P2K tournament browse: '.$e);api_error(500,'TOURNAMENT_BROWSE_FAILED','Tournament data is temporarily unavailable.');}
