<?php
declare(strict_types=1);

namespace P2K\TeamPoints;

use PDO;

/** v2.11.0 Green-native operational freshness projection. */
final class GreenFreshnessService
{
    public function __construct(private readonly PDO $core, private readonly PDO $analytics, private readonly string $clubSlug) {}

    private function one(PDO $pdo, string $sql, array $args = []): array
    {
        $q = $pdo->prepare($sql); $q->execute($args); $row = $q->fetch(PDO::FETCH_ASSOC); return is_array($row) ? $row : [];
    }
    private function optionalOne(PDO $pdo, string $sql, array $args = []): array
    {
        try { return $this->one($pdo,$sql,$args); } catch (\Throwable $e) { error_log('P2K Green freshness optional query: '.$e->getMessage()); return []; }
    }
    private static function epoch(mixed $value): ?int
    {
        $raw=trim((string)($value??'')); if($raw==='')return null; $time=strtotime($raw.(preg_match('/(?:Z|[+-]\d\d:?\d\d)$/',$raw)?'':' UTC')); return $time===false?null:$time;
    }
    private static function ageSeconds(mixed $value): ?int { $time=self::epoch($value); return $time===null?null:max(0,time()-$time); }
    private static function percent(int $good,int $total): float { return $total>0?round(100*max(0,min($total,$good))/$total,1):100.0; }
    private function greenApp(): array
    {
        try { if(class_exists('P2K\\Green\\GreenConfig')){$cfg=\P2K\Green\GreenConfig::load(false);return is_array($cfg['app']??null)?$cfg['app']:[];} } catch(\Throwable $ignored){} return [];
    }
    private function tournamentFreshness(): array
    {
        $root=dirname(__DIR__,3);$path=$root.'/data/tournaments/archive.json';$data=null;$source='none';
        if(is_file($path)){$decoded=json_decode((string)@file_get_contents($path),true);if(is_array($decoded)){$data=$decoded;$source='archive';}}
        if(!is_array($data)){$backups=glob(dirname($path).'/backups/archive-*.json')?:[];rsort($backups,SORT_STRING);foreach($backups as $backup){$decoded=json_decode((string)@file_get_contents($backup),true);if(is_array($decoded)&&(!empty($decoded['tournaments'])||!empty($decoded['reinitializedAt']))){$data=$decoded;$source='backup';break;}}}
        if(!is_array($data))return ['observed_at'=>null,'age_seconds'=>null,'status_checked_at'=>null,'status_age_seconds'=>null,'tournament_count'=>null,'source'=>$source,'target_seconds'=>600];
        $last=$data['lastStatusRefresh']??null;$observed=is_array($last)?($last['at']??null):(is_string($last)?$last:null);$status=$data['scanState']['lastStatusCheckAt']??(is_array($last)?($last['statusCheckedAt']??null):null);$observed??=$data['scanState']['lastSync']??($data['generatedAt']??null);$status??=$observed;if($observed===null&&is_file($path))$observed=gmdate('Y-m-d H:i:s',(int)filemtime($path));
        return ['observed_at'=>$observed,'age_seconds'=>self::ageSeconds($observed),'status_checked_at'=>$status,'status_age_seconds'=>self::ageSeconds($status),'tournament_count'=>is_array($data['tournaments']??null)?count($data['tournaments']):null,'source'=>$source,'target_seconds'=>600];
    }

    public function report(): array
    {
        $state=$this->optionalOne($this->core,'SELECT * FROM p2k_g_state WHERE club_slug=? LIMIT 1',[$this->clubSlug]);$greenApp=$this->greenApp();
        $statsTarget=max(3600,(int)($greenApp['stats_refresh_seconds']??259200));$historicalTarget=max(86400,(int)($greenApp['historical_match_recheck_seconds']??2592000));$currentTarget=max(60,min(3600,(int)($state['gffl_target_freshness_seconds']??1200)));$indexTarget=300;$rosterTarget=max(600,$currentTarget);$analyticsTarget=max(600,$currentTarget);
        $statsCutoff=gmdate('Y-m-d H:i:s',time()-$statsTarget);$currentCutoff=gmdate('Y-m-d H:i:s',time()-$currentTarget);$historicalCutoff=gmdate('Y-m-d H:i:s',time()-$historicalTarget);
        $players=$this->optionalOne($this->core,"SELECT COUNT(*) known_players,COALESCE(SUM(current_member=1),0) current_members,COALESCE(SUM(current_member=1 AND profile_checked_at IS NOT NULL),0) profile_checked,COALESCE(SUM(current_member=1 AND profile_checked_at IS NULL),0) profile_missing,COALESCE(SUM(current_member=1 AND stats_checked_at IS NOT NULL),0) stats_checked,COALESCE(SUM(current_member=1 AND stats_checked_at IS NULL),0) stats_never,COALESCE(SUM(current_member=1 AND (stats_checked_at IS NULL OR stats_checked_at<?)),0) stats_due,COALESCE(SUM(current_member=1 AND stats_checked_at>=?),0) stats_fresh,COALESCE(SUM(current_member=1 AND (daily_rating IS NOT NULL OR chess960_rating IS NOT NULL)),0) rated,COALESCE(SUM(current_member=1 AND (daily_rating IS NOT NULL OR chess960_rating IS NOT NULL) AND stats_checked_at>=?),0) fresh_ratings,COALESCE(SUM(current_member=1 AND avatar_url IS NOT NULL AND avatar_url<>''),0) avatars,MIN(CASE WHEN current_member=1 AND stats_checked_at IS NOT NULL THEN stats_checked_at END) oldest_stats_at,MAX(CASE WHEN current_member=1 THEN last_seen_roster_at END) newest_roster_seen_at FROM p2k_g_players",[$statsCutoff,$statsCutoff,$statsCutoff]);
        $matches=$this->optionalOne($this->core,"SELECT COALESCE(SUM(club_verified=1 AND time_class='daily' AND is_void=0),0) eligible_total,COALESCE(SUM(club_verified=1 AND time_class='daily' AND is_void=0 AND status IN ('registered','in_progress')),0) current_total,COALESCE(SUM(club_verified=1 AND time_class='daily' AND is_void=0 AND status IN ('registered','in_progress') AND (last_verified_at IS NULL OR last_verified_at<?)),0) current_due,COALESCE(SUM(club_verified=1 AND time_class='daily' AND is_void=0 AND status IN ('registered','in_progress') AND last_verified_at IS NULL),0) current_never_verified,MIN(CASE WHEN club_verified=1 AND time_class='daily' AND is_void=0 AND status IN ('registered','in_progress') AND (last_verified_at IS NULL OR last_verified_at<?) THEN COALESCE(last_verified_at,created_at) END) oldest_current_due_at,COALESCE(SUM(club_verified=1 AND time_class='daily' AND is_void=0 AND status='finished'),0) historical_total,COALESCE(SUM(club_verified=1 AND time_class='daily' AND is_void=0 AND status='finished' AND (last_verified_at IS NULL OR last_verified_at<?)),0) historical_due,COALESCE(SUM(retry_after IS NOT NULL AND retry_after>UTC_TIMESTAMP()),0) retry_blocked,COALESCE(SUM(status='unavailable'),0) unavailable FROM p2k_g_matches",[$currentCutoff,$currentCutoff,$historicalCutoff]);
        $boards=$this->optionalOne($this->core,"SELECT COUNT(*) eligible_total,COALESCE(SUM(m.status IN ('registered','in_progress')),0) active_total,COALESCE(SUM(m.status IN ('registered','in_progress') AND b.needs_refresh=1),0) active_due,COALESCE(SUM(m.status='finished'),0) finished_total,COALESCE(SUM(m.status='finished' AND b.state='finished' AND b.finished_game_count>=2 AND b.needs_refresh=0),0) finished_verified,COALESCE(SUM(m.status='finished' AND NOT (b.state='finished' AND b.finished_game_count>=2 AND b.needs_refresh=0)),0) finished_unresolved,COALESCE(SUM(b.needs_refresh=1 AND (b.retry_after IS NULL OR b.retry_after<=UTC_TIMESTAMP())),0) due_now,COALESCE(SUM(b.needs_refresh=1 AND b.retry_after>UTC_TIMESTAMP()),0) retry_blocked,COALESCE(SUM(b.state='unavailable'),0) unavailable,MIN(CASE WHEN b.needs_refresh=1 AND (b.retry_after IS NULL OR b.retry_after<=UTC_TIMESTAMP()) THEN COALESCE(b.last_verified_at,b.updated_at) END) oldest_due_at,MIN(CASE WHEN m.status='finished' AND NOT (b.state='finished' AND b.finished_game_count>=2 AND b.needs_refresh=0) THEN COALESCE(b.last_verified_at,b.updated_at) END) oldest_finished_unresolved_at FROM p2k_g_boards b JOIN p2k_g_matches m ON m.match_id=b.match_id WHERE m.club_verified=1 AND m.time_class='daily' AND m.is_void=0 AND m.status IN ('registered','in_progress','finished')");
        $gffl=$this->optionalOne($this->core,"SELECT COALESCE(SUM(status='pending'),0) pending,COALESCE(SUM(status='pending' AND due_at<=UTC_TIMESTAMP()),0) due,MIN(CASE WHEN status='pending' AND due_at<=UTC_TIMESTAMP() THEN due_at END) oldest_due_at FROM p2k_g_gffl_match_debt");
        $claims=$this->optionalOne($this->core,"SELECT COALESCE(SUM(claim_until>UTC_TIMESTAMP()),0) active,COALESCE(SUM(next_retry_at>UTC_TIMESTAMP()),0) retry_waiting,COALESCE(SUM(last_error IS NOT NULL AND last_error<>''),0) with_error,MIN(CASE WHEN next_retry_at IS NOT NULL THEN next_retry_at END) oldest_retry_at FROM p2k_g_work_claims");
        $quick=['total'=>0,'completed'=>0,'pending'=>0,'deferred_transient'=>0];$cycleNo=(int)($state['cycle_no']??0);if($cycleNo>0)$quick=$this->optionalOne($this->core,"SELECT COUNT(*) total,COALESCE(SUM(status='completed'),0) completed,COALESCE(SUM(status='pending'),0) pending,COALESCE(SUM(status='completed' AND requeued_for_next=1 AND terminal_http_status IS NOT NULL AND terminal_http_status NOT IN (200,204,404,410)),0) deferred_transient FROM p2k_g_quick_board_cycle_items WHERE cycle_no=?",[$cycleNo])+$quick;
        $lastQuick=$this->optionalOne($this->core,"SELECT cycle_no,completed_at,status FROM p2k_g_cycles WHERE cycle_kind='quick' AND status='completed' ORDER BY cycle_no DESC LIMIT 1");$lastDeep=$this->optionalOne($this->core,"SELECT cycle_no,completed_at,status FROM p2k_g_cycles WHERE cycle_kind='deep' AND status='completed' ORDER BY cycle_no DESC LIMIT 1");$latestCompleted=$this->optionalOne($this->core,"SELECT cycle_no,completed_at FROM p2k_g_cycles WHERE status='completed' ORDER BY cycle_no DESC LIMIT 1");
        $analytics=$this->optionalOne($this->analytics,'SELECT source_cycle_no,rebuilt_at,updated_at FROM p2k_g_analytics_meta WHERE club_slug=? LIMIT 1',[$this->clubSlug]);$sourceCycle=(int)($analytics['source_cycle_no']??0);$completedCycle=(int)($latestCompleted['cycle_no']??0);$cycleLag=max(0,$completedCycle-$sourceCycle);$analyticsRebuiltAt=$analytics['rebuilt_at']??($state['last_analytics_rebuild']??null);$analyticsAge=self::ageSeconds($analyticsRebuiltAt);$tournaments=$this->tournamentFreshness();
        $currentMembers=(int)($players['current_members']??0);$statsDue=(int)($players['stats_due']??0);$statsFresh=max(0,$currentMembers-$statsDue);$rated=(int)($players['rated']??0);$freshRatings=(int)($players['fresh_ratings']??0);$avatars=(int)($players['avatars']??0);$currentMatches=(int)($matches['current_total']??0);$currentMatchesDue=(int)($matches['current_due']??0);$finishedBoards=(int)($boards['finished_total']??0);$finishedVerified=(int)($boards['finished_verified']??0);$boardDue=(int)($boards['due_now']??0);$workFailed=(int)($claims['with_error']??0)+(int)($boards['unavailable']??0);$workPending=$boardDue+(int)($gffl['due']??0)+(int)($quick['pending']??0);
        $green=['source'=>'green_native_core','targets'=>['roster_seconds'=>$rosterTarget,'club_index_seconds'=>$indexTarget,'stats_seconds'=>$statsTarget,'current_match_seconds'=>$currentTarget,'historical_match_seconds'=>$historicalTarget,'analytics_seconds'=>$analyticsTarget,'tournament_seconds'=>600],
            'roster'=>['last_fetch_at'=>$state['last_roster_fetch']??null,'age_seconds'=>self::ageSeconds($state['last_roster_fetch']??null),'target_seconds'=>$rosterTarget,'current_members'=>$currentMembers],
            'players'=>['current_members'=>$currentMembers,'profile_checked'=>(int)($players['profile_checked']??0),'profile_missing'=>(int)($players['profile_missing']??0),'stats_fresh'=>$statsFresh,'stats_due'=>$statsDue,'stats_never'=>(int)($players['stats_never']??0),'stats_fresh_percent'=>self::percent($statsFresh,$currentMembers),'rated'=>$rated,'rating_coverage_percent'=>self::percent($rated,$currentMembers),'fresh_ratings'=>$freshRatings,'fresh_rating_percent'=>self::percent($freshRatings,$currentMembers),'avatars'=>$avatars,'avatar_percent'=>self::percent($avatars,$currentMembers),'oldest_stats_at'=>$players['oldest_stats_at']??null],
            'matches'=>['last_index_fetch_at'=>$state['last_index_fetch']??null,'index_age_seconds'=>self::ageSeconds($state['last_index_fetch']??null),'current_total'=>$currentMatches,'current_fresh'=>max(0,$currentMatches-$currentMatchesDue),'current_due'=>$currentMatchesDue,'current_never_verified'=>(int)($matches['current_never_verified']??0),'current_fresh_percent'=>self::percent(max(0,$currentMatches-$currentMatchesDue),$currentMatches),'oldest_current_due_at'=>$matches['oldest_current_due_at']??null,'historical_total'=>(int)($matches['historical_total']??0),'historical_audit_due'=>(int)($matches['historical_due']??0),'retry_blocked'=>(int)($matches['retry_blocked']??0),'unavailable'=>(int)($matches['unavailable']??0)],
            'boards'=>['eligible_total'=>(int)($boards['eligible_total']??0),'active_total'=>(int)($boards['active_total']??0),'active_due'=>(int)($boards['active_due']??0),'finished_total'=>$finishedBoards,'finished_verified'=>$finishedVerified,'finished_unresolved'=>(int)($boards['finished_unresolved']??0),'finished_verified_percent'=>self::percent($finishedVerified,$finishedBoards),'due_now'=>$boardDue,'retry_blocked'=>(int)($boards['retry_blocked']??0),'unavailable'=>(int)($boards['unavailable']??0),'oldest_due_at'=>$boards['oldest_due_at']??null,'oldest_finished_unresolved_at'=>$boards['oldest_finished_unresolved_at']??null],
            'work'=>['gffl_pending'=>(int)($gffl['pending']??0),'gffl_due'=>(int)($gffl['due']??0),'gffl_oldest_due_at'=>$gffl['oldest_due_at']??null,'claims_active'=>(int)($claims['active']??0),'claims_retry_waiting'=>(int)($claims['retry_waiting']??0),'claims_with_error'=>(int)($claims['with_error']??0),'quick_cycle_total'=>(int)($quick['total']??0),'quick_cycle_completed'=>(int)($quick['completed']??0),'quick_cycle_pending'=>(int)($quick['pending']??0),'quick_cycle_deferred_transient'=>(int)($quick['deferred_transient']??0),'due_total'=>$workPending,'failed_total'=>$workFailed],
            'cycle'=>['cycle_no'=>$cycleNo,'mode'=>$state['mode']??null,'stage'=>$state['stage']??null,'cycle_kind'=>$state['cycle_kind']??null,'cycle_started_at'=>$state['cycle_started_at']??null,'cycle_completed_at'=>$state['cycle_completed_at']??null,'last_worker_start'=>$state['last_worker_start']??null,'last_worker_finish'=>$state['last_worker_finish']??null,'last_worker_status'=>$state['last_worker_status']??null,'last_error'=>$state['last_error']??null,'last_quick'=>$lastQuick,'last_deep'=>$lastDeep],
            'analytics'=>['source_cycle_no'=>$sourceCycle,'latest_completed_cycle_no'=>$completedCycle,'cycle_lag'=>$cycleLag,'rebuilt_at'=>$analyticsRebuiltAt,'age_seconds'=>$analyticsAge,'target_seconds'=>$analyticsTarget],'tournaments'=>$tournaments];
        return ['source'=>'green_native_core','green'=>$green,'coverage'=>['current_members'=>$currentMembers,'player_matches_due'=>$currentMatchesDue,'player_matches_never_checked'=>(int)($matches['current_never_verified']??0),'player_matches_fresh_percent'=>$green['matches']['current_fresh_percent'],'player_matches_operational_due'=>$currentMatchesDue,'player_matches_operational_fresh_percent'=>$green['matches']['current_fresh_percent'],'player_stats_due'=>$statsDue,'player_stats_never_checked'=>(int)($players['stats_never']??0),'player_stats_fresh_percent'=>$green['players']['stats_fresh_percent'],'player_stats_operational_due'=>$statsDue,'player_stats_operational_fresh_percent'=>$green['players']['stats_fresh_percent'],'rating_percent'=>$green['players']['rating_coverage_percent'],'fresh_rating_percent'=>$green['players']['fresh_rating_percent'],'avatar_percent'=>$green['players']['avatar_percent'],'finished_board_complete_percent'=>$green['boards']['finished_verified_percent'],'board_complete_percent'=>$green['boards']['finished_verified_percent'],'finished_boards_unresolved'=>$green['boards']['finished_unresolved'],'active_board_backlog'=>$green['boards']['active_due'],'boards_pending'=>$boardDue,'boards_failed'=>$workFailed,'queue_pending'=>$workPending,'queue_failed'=>$workFailed],
            'ages'=>['oldest_finished_unresolved_seconds'=>self::ageSeconds($boards['oldest_finished_unresolved_at']??null),'oldest_queue_seconds'=>self::ageSeconds($gffl['oldest_due_at']??($boards['oldest_due_at']??null)),'oldest_rating_seconds'=>self::ageSeconds($players['oldest_stats_at']??null),'core_analytics_lag_seconds'=>$analyticsAge],
            'core'=>['members_last_observed_at'=>$state['last_roster_fetch']??null,'club_index_last_observed_at'=>$state['last_index_fetch']??null,'core_generation'=>$cycleNo,'mode'=>$state['mode']??null,'stage'=>$state['stage']??null,'last_worker_finish'=>$state['last_worker_finish']??null,'last_worker_status'=>$state['last_worker_status']??null],'tournaments'=>$tournaments];
    }
}
