<?php
declare(strict_types=1);

namespace P2K\TeamPoints;

use PDO;

/** v2.10.9 durable MCA discovery + full arena acquisition worker. */
final class McaResultsCronService
{
    private readonly string $clubSlug;
    private readonly string $storageDir;

    public function __construct(private readonly PDO $pdo, private readonly Repository $repository)
    {
        $config=\p2k_tp_config();
        $this->clubSlug=strtolower((string)($config['app']['club_slug']??'promote-to-king'));
        $configured=trim((string)($config['app']['live_ranks_upload_dir']??''));
        $this->storageDir=$configured!==''?rtrim($configured,'/\\'):dirname(__DIR__,3).'/data/live-ranks/uploads';
    }

    public function status(): array
    {
        $this->ensureState();$this->seedHistoricalBacklog();
        $state=$this->stateRow();
        $counts=['pending'=>0,'running'=>0,'completed'=>0,'error'=>0];
        $q=$this->pdo->prepare('SELECT status,COUNT(*) n FROM p2k_lr_arena_acquisition WHERE club_slug=? GROUP BY status');$q->execute([$this->clubSlug]);
        foreach($q->fetchAll(PDO::FETCH_ASSOC)?:[] as $r)if(isset($counts[(string)$r['status']]))$counts[(string)$r['status']]=(int)$r['n'];
        $stage=[];$q=$this->pdo->prepare("SELECT stage,COUNT(*) n FROM p2k_lr_arena_acquisition WHERE club_slug=? AND status<>'completed' GROUP BY stage");$q->execute([$this->clubSlug]);foreach($q->fetchAll(PDO::FETCH_ASSOC)?:[] as $r)$stage[(string)$r['stage']]=(int)$r['n'];
        $gamesQ=$this->pdo->prepare('SELECT COUNT(*) FROM p2k_lr_arena_games WHERE club_slug=?');$gamesQ->execute([$this->clubSlug]);$games=(int)$gamesQ->fetchColumn();
        $perfQ=$this->pdo->prepare('SELECT (SELECT COUNT(*) FROM p2k_lr_arena_clubs WHERE club_slug=?),(SELECT COUNT(*) FROM p2k_lr_arena_players WHERE club_slug=?)');$perfQ->execute([$this->clubSlug,$this->clubSlug]);$perf=$perfQ->fetch(PDO::FETCH_NUM)?:[0,0];
        $errQ=$this->pdo->prepare("SELECT arena_id,arena_slug,arena_url,stage,attempts,last_error,updated_at FROM p2k_lr_arena_acquisition WHERE club_slug=? AND status='error' ORDER BY priority DESC,updated_at DESC LIMIT 100");$errQ->execute([$this->clubSlug]);
        $errors=array_map(static fn($r)=>['arena_id'=>(int)$r['arena_id'],'arena_slug'=>(string)$r['arena_slug'],'arena_url'=>(string)$r['arena_url'],'stage'=>(string)$r['stage'],'attempts'=>(int)$r['attempts'],'error'=>(string)($r['last_error']??''),'updated_at'=>(string)$r['updated_at']],$errQ->fetchAll(PDO::FETCH_ASSOC)?:[]);
        $total=array_sum($counts);$done=$counts['completed'];$workflow='current';if(($state['status']??'')==='running'&&($state['phase']??'')==='discovery')$workflow=!empty($state['last_error'])?'discovery_attention':'discovery';elseif($counts['running']+$counts['pending']>0)$workflow='acquisition';elseif($counts['error']>0)$workflow='attention';
        $missingDatesQ=$this->pdo->prepare('SELECT COUNT(*) FROM p2k_lr_files WHERE club_slug=? AND actual_event_date IS NULL');$missingDatesQ->execute([$this->clubSlug]);
        return $state+[
            'mode'=>'v2109_full_arena_acquisition','workflow_status'=>$workflow,'queue'=>$counts,'hydration_queue'=>$counts,'stage_queue'=>$stage,'errors'=>$errors,
            'progress_percent'=>$total>0?round(100*$done/$total,1):100.0,'historical_missing_dates'=>(int)$missingDatesQ->fetchColumn(),
            'arena_backlog_total'=>$total,'arena_backlog_remaining'=>$counts['pending']+$counts['running']+$counts['error'],'games_stored'=>$games,'club_rows_stored'=>(int)$perf[0],'player_rows_stored'=>(int)$perf[1],
            'serial'=>true,'request_spacing_ms'=>1000,'worker_frequency'=>'every_minute','worker_slice_seconds'=>55,'new_arena_priority'=>true,
        ];
    }

    public function runDiscovery(int $maxSeconds=12,bool $force=false): array
    {
        return $this->withGlobalLock(function()use($maxSeconds,$force){$this->ensureState();$this->seedHistoricalBacklog();$state=$this->stateRow();
            if($force&&($state['status']??'')!=='running'){$this->pdo->prepare('UPDATE p2k_lr_sync_state SET next_scan_at=UTC_TIMESTAMP(),last_error=NULL,updated_at=UTC_TIMESTAMP() WHERE club_slug=?')->execute([$this->clubSlug]);$state=$this->stateRow();}
            if(($state['status']??'')!=='running'||($state['phase']??'')!=='discovery'){$due=empty($state['next_scan_at'])||(strtotime((string)$state['next_scan_at'].' UTC')?:0)<=time();if(!$due)return $this->status();$this->beginDiscoveryCycle();}
            $deadline=microtime(true)+max(4,min(60,$maxSeconds));while(microtime(true)<$deadline-6.0){$state=$this->stateRow();if(($state['status']??'')!=='running'||($state['phase']??'')!=='discovery')break;if(!$this->discoveryStep($state,$deadline))break;}return $this->status();});
    }

    /** Compatibility name retained for Admin API; now runs the full arena acquisition worker. */
    public function runHydration(int $maxSeconds=55): array
    {
        return $this->withGlobalLock(function()use($maxSeconds){$this->ensureState();$this->ensureStorage();$this->seedHistoricalBacklog();$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET status='pending' WHERE club_slug=? AND status='running'")->execute([$this->clubSlug]);
            $deadline=microtime(true)+max(5,min(55,$maxSeconds));$steps=0;$csvAdded=0;
            while(microtime(true)<$deadline-6.0){$item=$this->nextAcquisitionItem();if($item===null)break;$r=$this->acquisitionStep($item,$deadline);$steps++;if(!empty($r['csv_added']))$csvAdded++;}
            if($csvAdded>0&&$this->rebuildRequired()&&microtime(true)<$deadline-6.0){try{$service=new LiveRanksService($this->pdo,$this->repository,new ChessApi($this->repository));$service->startProcessing($deadline-1.0);$this->pdo->prepare('UPDATE p2k_lr_sync_state SET rebuild_required=0,updated_at=UTC_TIMESTAMP() WHERE club_slug=?')->execute([$this->clubSlug]);}catch(\Throwable $e){$this->pdo->prepare('UPDATE p2k_lr_sync_state SET last_error=?,updated_at=UTC_TIMESTAMP() WHERE club_slug=?')->execute([substr($e->getMessage(),0,4000),$this->clubSlug]);}}
            return ['steps'=>$steps,'csv_added'=>$csvAdded,'sync'=>$this->status()];});
    }

    public function retryHydrationErrors(): array
    {return $this->withGlobalLock(function(){$q=$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET status='pending',last_error=NULL,updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND status='error'");$q->execute([$this->clubSlug]);return ['requeued'=>$q->rowCount(),'sync'=>$this->status()];});}

    public function backfillHistoricalDates(int $maxSeconds=120): array
    {return $this->withGlobalLock(function()use($maxSeconds){$deadline=microtime(true)+max(5,min(600,$maxSeconds));$updated=0;$errors=[];$q=$this->pdo->prepare('SELECT id,original_name,arena_id,arena_slug,event_url FROM p2k_lr_files WHERE club_slug=? AND actual_event_date IS NULL ORDER BY COALESCE(arena_id,0) DESC,id DESC');$q->execute([$this->clubSlug]);foreach($q->fetchAll(PDO::FETCH_ASSOC)?:[] as $file){if(microtime(true)>=$deadline-6)break;$id=$this->fileIdentity($file);if($id===null)continue;try{$date=$this->dateFromArenaPage($id['arena_url'],$deadline);if($date['event_date']===null){$index=$this->findArenaOnIndex($id['arena_id'],$deadline);if($index!==null)$date=$index;}if($date['event_date']===null)throw new \RuntimeException('No MCA date found on arena page or club index.');$u=$this->pdo->prepare('UPDATE p2k_lr_files SET actual_event_date=?,event_date_updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND id=? AND actual_event_date IS NULL');$u->execute([$date['event_date'],$this->clubSlug,(int)$file['id']]);$updated+=$u->rowCount();}catch(\Throwable $e){$errors[]=['arena_id'=>$id['arena_id'],'error'=>$e->getMessage()];}}if($updated>0)(new LiveRanksService($this->pdo,$this->repository,new ChessApi($this->repository)))->recomputeEventDates();return ['updated'=>$updated,'errors'=>$errors,'manual_only'=>true];});}

    private function seedHistoricalBacklog(): void
    {
        $this->ensureState();
        $state=$this->stateRow();
        if(!empty($state['arena_backfill_seeded_at']))return;
        $q=$this->pdo->prepare('SELECT id,original_name,arena_id,arena_slug,event_url,csv_url,actual_event_date,effective_event_date,event_date_precision FROM p2k_lr_files WHERE club_slug=? ORDER BY id');$q->execute([$this->clubSlug]);
        $ins=$this->pdo->prepare("INSERT IGNORE INTO p2k_lr_arena_acquisition(club_slug,arena_id,arena_slug,arena_url,csv_url,source_kind,priority,status,stage,results_source,needs_clubs,needs_players,event_date,date_precision,discovered_at,updated_at) VALUES(?,?,?,?,?,'historical',10,'pending','arena','stored',1,1,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP())");
        foreach($q->fetchAll(PDO::FETCH_ASSOC)?:[] as $f){$x=$this->fileIdentity($f);if($x===null)continue;$date=trim((string)($f['actual_event_date']??''));$precision=$date!==''?'known':(string)($f['event_date_precision']??'unknown');$ins->execute([$this->clubSlug,$x['arena_id'],$x['arena_slug'],$x['arena_url'],trim((string)($f['csv_url']??''))?:($x['arena_url'].'/download-results'),$date!==''?$date:null,$precision?:'unknown']);}
        $this->pdo->prepare('UPDATE p2k_lr_sync_state SET arena_backfill_seeded_at=UTC_TIMESTAMP(),updated_at=UTC_TIMESTAMP() WHERE club_slug=?')->execute([$this->clubSlug]);
    }

    private function beginDiscoveryCycle(): void
    {$q=$this->pdo->prepare('SELECT GREATEST(COALESCE((SELECT MAX(arena_id) FROM p2k_lr_files WHERE club_slug=?),0),COALESCE((SELECT MAX(arena_id) FROM p2k_lr_arena_acquisition WHERE club_slug=?),0))');$q->execute([$this->clubSlug,$this->clubSlug]);$boundary=(int)$q->fetchColumn();$this->pdo->prepare("UPDATE p2k_lr_sync_state SET status='running',phase='discovery',total_events=0,checked_events=0,csv_found=0,csv_added=0,dates_added=0,error_count=0,request_count=0,current_stage='index:1',high_water_arena_id=?,started_at=UTC_TIMESTAMP(),finished_at=NULL,last_error=NULL,last_scan_at=UTC_TIMESTAMP(),next_scan_at=NULL,updated_at=UTC_TIMESTAMP() WHERE club_slug=?")->execute([$boundary,$this->clubSlug]);}

    private function discoveryStep(array $state,float $deadline): bool
    {$stage=(string)($state['current_stage']??'index:1');$page=preg_match('/^index:(\d+)$/',$stage,$m)?max(1,(int)$m[1]):1;$boundary=(int)($state['high_water_arena_id']??0);try{$parsed=McaIndexParser::parse((string)$this->httpGet($this->indexUrl($page),$deadline)['body'],$page);if($parsed['events']===[])throw new \RuntimeException('MCA index page contained no arena links.');$reached=false;$inserted=0;$ins=$this->pdo->prepare("INSERT INTO p2k_lr_arena_acquisition(club_slug,arena_id,arena_slug,arena_url,csv_url,source_kind,priority,status,stage,results_source,needs_clubs,needs_players,event_start_at,event_date,date_precision,discovered_at,updated_at) VALUES(?,?,?,?,?,'discovery',100,'pending','arena','unknown',1,1,?,?,?,UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE arena_slug=VALUES(arena_slug),arena_url=VALUES(arena_url),csv_url=COALESCE(NULLIF(VALUES(csv_url),''),csv_url),priority=GREATEST(priority,100),event_start_at=COALESCE(VALUES(event_start_at),event_start_at),event_date=COALESCE(VALUES(event_date),event_date),date_precision=IF(VALUES(event_date) IS NOT NULL,VALUES(date_precision),date_precision),updated_at=UTC_TIMESTAMP()");foreach($parsed['events'] as $e){$id=(int)$e['arena_id'];if($boundary>0&&$id<=$boundary){$reached=true;continue;}$ins->execute([$this->clubSlug,$id,(string)$e['arena_slug'],(string)$e['arena_url'],(string)$e['csv_url'],$e['event_start_at'],$e['event_date'],(string)$e['date_precision']]);$inserted+=$ins->rowCount()>0?1:0;}$this->pdo->prepare('UPDATE p2k_lr_sync_state SET total_events=total_events+?,checked_events=checked_events+?,current_stage=?,last_error=NULL,updated_at=UTC_TIMESTAMP() WHERE club_slug=?')->execute([$inserted,count($parsed['events']),'index:'.($page+1),$this->clubSlug]);if($reached||($boundary===0&&empty($parsed['has_next']))){$this->completeDiscoveryCycle();return false;}if(empty($parsed['has_next']))throw new \RuntimeException('MCA index pagination ended before boundary '.$boundary.' was reached.');return true;}catch(\Throwable $e){$this->pdo->prepare("UPDATE p2k_lr_sync_state SET status='running',phase='discovery',error_count=error_count+1,last_error=?,updated_at=UTC_TIMESTAMP() WHERE club_slug=?")->execute([substr($e->getMessage(),0,4000),$this->clubSlug]);return false;}}
    private function completeDiscoveryCycle(): void{$q=$this->pdo->prepare('SELECT COALESCE(MAX(arena_id),0) FROM p2k_lr_arena_acquisition WHERE club_slug=?');$q->execute([$this->clubSlug]);$max=(int)$q->fetchColumn();$this->pdo->prepare("UPDATE p2k_lr_sync_state SET status='completed',phase='discovery_complete',high_water_arena_id=?,current_stage=NULL,finished_at=UTC_TIMESTAMP(),next_scan_at=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 12 HOUR),last_error=NULL,updated_at=UTC_TIMESTAMP() WHERE club_slug=?")->execute([$max,$this->clubSlug]);}

    private function nextAcquisitionItem(): ?array{$q=$this->pdo->prepare("SELECT * FROM p2k_lr_arena_acquisition WHERE club_slug=? AND status='pending' ORDER BY priority DESC,arena_id DESC LIMIT 1");$q->execute([$this->clubSlug]);$r=$q->fetch(PDO::FETCH_ASSOC);return is_array($r)?$r:null;}

    private function acquisitionStep(array $item,float $deadline): array
    {
        $id=(int)$item['arena_id'];$stage=(string)$item['stage'];$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET status='running',attempts=attempts+1,started_at=COALESCE(started_at,UTC_TIMESTAMP()),last_error=NULL,updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([$this->clubSlug,$id]);
        try{
            if($stage==='arena'){$html=(string)$this->httpGet((string)$item['arena_url'],$deadline)['body'];$p=McaArenaParser::arenaPage($html);$date=$p['event_date']??($item['event_date']??null);$start=$p['event_start_at']??($item['event_start_at']??null);$precision=($p['event_date']??null)!==null?(string)$p['date_precision']:(string)($item['date_precision']??'unknown');$csv=(string)($p['csv_url']??'');if($csv==='')$csv=(string)($item['csv_url']??'');if($csv==='')$csv=rtrim((string)$item['arena_url'],'/').'/download-results';$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET arena_page_done=1,csv_url=?,advertised_players=?,max_eligible_scorers=?,arena_rating=?,clubs_total_pages=?,players_total_pages=?,pairings_total_pages=?,event_start_at=COALESCE(?,event_start_at),event_date=COALESCE(?,event_date),date_precision=?,stage='results',status='pending',updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([$csv,$p['advertised_players'],$p['max_eligible_scorers'],$p['rating'],max(1,(int)$p['clubs_pages']),max(1,(int)$p['players_pages']),max(1,(int)$p['pairings_pages']),$start,$date,$precision,$this->clubSlug,$id]);if($date!==null)$this->applyDateToFile($id,(string)$date);return [];}
            if($stage==='results'){return $this->processResults($item,$deadline);}
            if($stage==='clubs'){$page=max(1,(int)$item['clubs_next_page']);$html=(string)$this->httpGet($this->dimensionUrl((string)$item['arena_url'],'clubs',$page),$deadline)['body'];$rows=McaArenaParser::clubRows($html);if($rows===[])throw new \RuntimeException('Club Results page '.$page.' contained no rows.');if($page===1)$this->pdo->prepare('DELETE FROM p2k_lr_arena_clubs WHERE club_slug=? AND arena_id=?')->execute([$this->clubSlug,$id]);$this->insertClubRows($id,$rows,'html');$total=max($page,(int)$item['clubs_total_pages']);$next=$page+1;if($next>$total){$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET needs_clubs=0,clubs_next_page=?,stage=IF(needs_players=1,'players','pairings'),status='pending',updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([$next,$this->clubSlug,$id]);}else{$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET clubs_next_page=?,status='pending',updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([$next,$this->clubSlug,$id]);}return [];}
            if($stage==='players'){$page=max(1,(int)$item['players_next_page']);$html=(string)$this->httpGet($this->dimensionUrl((string)$item['arena_url'],'players',$page),$deadline)['body'];$rows=McaArenaParser::playerRows($html);if($rows===[])throw new \RuntimeException('Player Results page '.$page.' contained no rows.');if($page===1)$this->pdo->prepare('DELETE FROM p2k_lr_arena_players WHERE club_slug=? AND arena_id=?')->execute([$this->clubSlug,$id]);$this->insertPlayerRows($id,$rows,'html');$total=max($page,(int)$item['players_total_pages']);$next=$page+1;if($next>$total){$added=0;if($this->existingFile($id,(string)$item['arena_slug'])===null){$this->storeHtmlFallbackCsv($item);$added=1;}$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET needs_players=0,players_next_page=?,results_source=IF(results_source='csv','mixed','html'),stage='pairings',status='pending',updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([$next,$this->clubSlug,$id]);return ['csv_added'=>$added];}$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET players_next_page=?,status='pending',updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([$next,$this->clubSlug,$id]);return [];}
            if($stage==='pairings'){$page=max(1,(int)$item['pairings_next_page']);$html=(string)$this->httpGet($this->dimensionUrl((string)$item['arena_url'],'pairings',$page),$deadline)['body'];$rows=McaArenaParser::pairingRows($html);if($rows===[])throw new \RuntimeException('Pairings page '.$page.' contained no games.');if($page===1)$this->pdo->prepare('DELETE FROM p2k_lr_arena_games WHERE club_slug=? AND arena_id=?')->execute([$this->clubSlug,$id]);$this->insertGameRows($id,$page,$rows);$total=max($page,(int)$item['pairings_total_pages']);$next=$page+1;if($next>$total){$c=$this->pdo->prepare('SELECT COUNT(*) FROM p2k_lr_arena_games WHERE club_slug=? AND arena_id=?');$c->execute([$this->clubSlug,$id]);$games=(int)$c->fetchColumn();$needDate=empty($item['event_date']);$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET pairings_next_page=?,game_count=?,stage=?,status='pending',updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([$next,$games,$needDate?'date_index':'done',$this->clubSlug,$id]);}else{$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET pairings_next_page=?,status='pending',updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([$next,$this->clubSlug,$id]);}return [];}
            if($stage==='date_index'){$page=max(1,(int)($item['date_index_next_page']??1));$parsed=McaIndexParser::parse((string)$this->httpGet($this->indexUrl($page),$deadline)['body'],$page);if($parsed['events']===[])throw new \RuntimeException('MCA index page '.$page.' contained no arena rows during date fallback.');$oldest=PHP_INT_MAX;foreach($parsed['events'] as $e){$seen=(int)$e['arena_id'];$oldest=min($oldest,$seen);if($seen!==$id)continue;if(empty($e['event_date']))throw new \RuntimeException('Arena was found on the MCA index but its date was unavailable.');$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET event_start_at=?,event_date=?,date_precision=?,date_index_next_page=?,stage='done',status='pending',updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([$e['event_start_at'],$e['event_date'],$e['date_precision'],$page,$this->clubSlug,$id]);$this->applyDateToFile($id,(string)$e['event_date']);return [];}$hasNext=!empty($parsed['has_next']);if($oldest<$id||!$hasNext)throw new \RuntimeException('Arena date unavailable on arena page and MCA index.');$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET date_index_next_page=?,status='pending',updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([$page+1,$this->clubSlug,$id]);return [];}
            if($stage==='done'){$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET status='completed',completed_at=UTC_TIMESTAMP(),last_error=NULL,updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([$this->clubSlug,$id]);return [];}
            throw new \RuntimeException('Unknown MCA acquisition stage '.$stage.'.');
        }catch(\Throwable $e){$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET status='error',last_error=?,updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([substr($e->getMessage(),0,4000),$this->clubSlug,$id]);return ['error'=>$e->getMessage()];}
    }

    private function processResults(array $item,float $deadline): array
    {$id=(int)$item['arena_id'];$existing=$this->existingFile($id,(string)$item['arena_slug']);$parsed=null;$added=0;$error=null;if($existing!==null){try{$body=file_get_contents($this->storageDir.'/'.basename((string)$existing['stored_name']));if($body===false)throw new \RuntimeException('Stored Results CSV file is missing.');$parsed=McaArenaParser::resultsCsv($body);}catch(\Throwable $e){$error=$e->getMessage();}}else{try{$body=(string)$this->httpGet((string)$item['csv_url'],$deadline)['body'];$this->validateResultsCsv($body);$parsed=McaArenaParser::resultsCsv($body);$date=['event_date'=>$item['event_date']??null,'event_start_at'=>$item['event_start_at']??null,'date_precision'=>$item['date_precision']??'unknown'];$this->storeAutomaticCsv($item,$body,$date,'auto');$added=1;}catch(\Throwable $e){$error=$e->getMessage();}}
        $clubs=is_array($parsed)?($parsed['clubs']??[]):[];$players=is_array($parsed)?($parsed['players']??[]):[];if($clubs!==[]){$this->replaceClubRows($id,$clubs,'csv');}if($players!==[]){$this->replacePlayerRows($id,$players,'csv');}
        $needClubs=$clubs===[]?1:0;$needPlayers=$players===[]?1:0;$source=($clubs!==[]||$players!==[])?'csv':'html';$next=$needClubs?'clubs':($needPlayers?'players':'pairings');$this->pdo->prepare("UPDATE p2k_lr_arena_acquisition SET results_source=?,needs_clubs=?,needs_players=?,stage=?,status='pending',last_error=?,updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=?")->execute([$source,$needClubs,$needPlayers,$next,$error!==null?substr('CSV fallback: '.$error,0,4000):null,$this->clubSlug,$id]);if($added){$this->pdo->prepare('UPDATE p2k_lr_sync_state SET csv_found=csv_found+1,csv_added=csv_added+1,rebuild_required=1,updated_at=UTC_TIMESTAMP() WHERE club_slug=?')->execute([$this->clubSlug]);}return ['csv_added'=>$added];}

    private function replaceClubRows(int $id,array $rows,string $source): void{$this->pdo->beginTransaction();try{$this->pdo->prepare('DELETE FROM p2k_lr_arena_clubs WHERE club_slug=? AND arena_id=?')->execute([$this->clubSlug,$id]);$this->insertClubRows($id,$rows,$source);$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    private function insertClubRows(int $id,array $rows,string $source): void{$q=$this->pdo->prepare('INSERT INTO p2k_lr_arena_clubs(club_slug,arena_id,result_key,result_club,result_club_slug,rank_value,total_players,score,source_kind,captured_at) VALUES(?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE result_club=VALUES(result_club),result_club_slug=VALUES(result_club_slug),rank_value=VALUES(rank_value),total_players=VALUES(total_players),score=VALUES(score),source_kind=VALUES(source_kind),captured_at=UTC_TIMESTAMP()');foreach($rows as $r){$name=trim((string)($r['club']??''));$slug=trim((string)($r['club_slug']??''));$key=$slug!==''?$slug:substr(hash('sha256',strtolower($name)),0,48);$q->execute([$this->clubSlug,$id,$key,$name!==''?$name:$slug,$slug!==''?$slug:null,$r['rank']??null,(int)($r['total_players']??0),(float)($r['score']??0),$source]);}}
    private function replacePlayerRows(int $id,array $rows,string $source): void{$this->pdo->beginTransaction();try{$this->pdo->prepare('DELETE FROM p2k_lr_arena_players WHERE club_slug=? AND arena_id=?')->execute([$this->clubSlug,$id]);$this->insertPlayerRows($id,$rows,$source);$this->pdo->commit();}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}
    private function insertPlayerRows(int $id,array $rows,string $source): void{$q=$this->pdo->prepare('INSERT INTO p2k_lr_arena_players(club_slug,arena_id,username_key,username,rank_value,rating,result_club,result_club_slug,score,wins,draws,losses,byes,streak,most_wins,source_kind,captured_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE username=VALUES(username),rank_value=VALUES(rank_value),rating=VALUES(rating),result_club=VALUES(result_club),result_club_slug=VALUES(result_club_slug),score=VALUES(score),wins=VALUES(wins),draws=VALUES(draws),losses=VALUES(losses),byes=VALUES(byes),streak=VALUES(streak),most_wins=VALUES(most_wins),source_kind=VALUES(source_kind),captured_at=UTC_TIMESTAMP()');foreach($rows as $r){$u=trim((string)($r['username']??''));if($u==='')continue;$q->execute([$this->clubSlug,$id,strtolower($u),$u,$r['rank']??null,$r['rating']??null,$r['club']??null,$r['club_slug']??null,(float)($r['score']??0),$r['wins']??null,$r['draws']??null,$r['losses']??null,$r['bye']??null,$r['streak']??null,$r['most_wins']??null,$source]);}}
    private function insertGameRows(int $id,int $page,array $rows): void{$q=$this->pdo->prepare('INSERT INTO p2k_lr_arena_games(club_slug,arena_id,game_id,game_url,white_username_key,white_username,white_rating,black_username_key,black_username,black_rating,result,source_page,captured_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE game_url=VALUES(game_url),white_username_key=VALUES(white_username_key),white_username=VALUES(white_username),white_rating=VALUES(white_rating),black_username_key=VALUES(black_username_key),black_username=VALUES(black_username),black_rating=VALUES(black_rating),result=VALUES(result),source_page=VALUES(source_page),captured_at=UTC_TIMESTAMP()');foreach($rows as $r)$q->execute([$this->clubSlug,$id,(int)$r['game_id'],$r['game_url'],$r['white_key'],$r['white'],$r['white_rating'],$r['black_key'],$r['black'],$r['black_rating'],$r['result'],$page]);}

    private function storeHtmlFallbackCsv(array $item): void{$q=$this->pdo->prepare('SELECT rank_value,username,result_club,score,wins,draws,losses,streak,most_wins FROM p2k_lr_arena_players WHERE club_slug=? AND arena_id=? ORDER BY COALESCE(rank_value,999999),username_key');$q->execute([$this->clubSlug,(int)$item['arena_id']]);$rows=$q->fetchAll(PDO::FETCH_ASSOC)?:[];if($rows===[])throw new \RuntimeException('Cannot create HTML fallback Results source without player rows.');$fh=fopen('php://temp','w+');fputcsv($fh,['rank','username','club','score','wins','draws','losses','longest streak','most wins']);foreach($rows as $r)fputcsv($fh,[$r['rank_value'],$r['username'],$r['result_club'],$r['score'],$r['wins'],$r['draws'],$r['losses'],$r['streak'],$r['most_wins']]);rewind($fh);$body=stream_get_contents($fh);fclose($fh);$this->storeAutomaticCsv($item,(string)$body,['event_date'=>$item['event_date']??null,'event_start_at'=>$item['event_start_at']??null,'date_precision'=>$item['date_precision']??'unknown'],'html-fallback');$this->pdo->prepare('UPDATE p2k_lr_sync_state SET rebuild_required=1,updated_at=UTC_TIMESTAMP() WHERE club_slug=?')->execute([$this->clubSlug]);}
    private function storeAutomaticCsv(array $item,string $body,array $date,string $origin): void{$this->ensureStorage();$stored=bin2hex(random_bytes(12)).'.csv';$path=$this->storageDir.'/'.$stored;if(file_put_contents($path,$body,LOCK_EX)===false)throw new \RuntimeException('Unable to store discovered MCA Results source.');@chmod($path,0660);try{$ins=$this->pdo->prepare("INSERT INTO p2k_lr_files(club_slug,original_name,stored_name,sha256,size_bytes,uploaded_at,arena_id,arena_slug,event_url,csv_url,source_origin,source_fetched_at,actual_event_date,effective_event_date,event_date_precision,event_date_updated_at,status,row_count,p2k_row_count) VALUES(?,?,?,?,?,UTC_TIMESTAMP(),?,?,?,?,?,UTC_TIMESTAMP(),?,?,?,UTC_TIMESTAMP(),'uploaded',0,0)");$eventDate=$date['event_date']??null;$ins->execute([$this->clubSlug,(string)$item['arena_slug'].'.csv',$stored,hash('sha256',$body),strlen($body),(int)$item['arena_id'],(string)$item['arena_slug'],(string)$item['arena_url'],(string)($item['csv_url']??''),$origin,$eventDate,$eventDate,$eventDate!==null?'known':'upload-fallback']);}catch(\Throwable $e){@unlink($path);throw $e;}$this->invalidateDerivedMca();}
    private function invalidateDerivedMca(): void{$this->pdo->prepare('DELETE FROM p2k_lr_players WHERE club_slug=?')->execute([$this->clubSlug]);$this->pdo->prepare('DELETE FROM p2k_lr_arena_stats WHERE club_slug=?')->execute([$this->clubSlug]);$this->pdo->prepare("INSERT INTO p2k_lr_processing_state(club_slug,status,phase,total_files,processed_files,total_players,checked_players,possible_renamed,closed_accounts,started_at,updated_at,finished_at,last_error) VALUES(?,'idle','files_changed',0,0,0,0,0,0,NULL,UTC_TIMESTAMP(),NULL,NULL) ON DUPLICATE KEY UPDATE status='idle',phase='files_changed',total_files=0,processed_files=0,total_players=0,checked_players=0,possible_renamed=0,closed_accounts=0,started_at=NULL,updated_at=UTC_TIMESTAMP(),finished_at=NULL,last_error=NULL")->execute([$this->clubSlug]);}

    private function validateResultsCsv(string $body): void{$p=McaArenaParser::resultsCsv($body);if($body===''||strlen($body)<20||empty($p['valid'])||empty($p['players']))throw new \RuntimeException('Discovered MCA Results CSV is empty, unrecognized, or missing Player Results.');}
    private function existingFile(int $id,string $slug): ?array{$q=$this->pdo->prepare('SELECT * FROM p2k_lr_files WHERE club_slug=? AND (arena_id=? OR original_name=?) LIMIT 1');$q->execute([$this->clubSlug,$id,$slug.'.csv']);$r=$q->fetch(PDO::FETCH_ASSOC);return is_array($r)?$r:null;}
    private function applyDateToFile(int $arenaId,string $date): void{$q=$this->pdo->prepare('UPDATE p2k_lr_files SET actual_event_date=?,event_date_updated_at=UTC_TIMESTAMP() WHERE club_slug=? AND arena_id=? AND actual_event_date IS NULL');$q->execute([$date,$this->clubSlug,$arenaId]);if($q->rowCount()>0)$this->pdo->prepare('UPDATE p2k_lr_sync_state SET dates_added=dates_added+1,updated_at=UTC_TIMESTAMP() WHERE club_slug=?')->execute([$this->clubSlug]);}
    private function rebuildRequired(): bool{$q=$this->pdo->prepare('SELECT rebuild_required FROM p2k_lr_sync_state WHERE club_slug=?');$q->execute([$this->clubSlug]);return (int)$q->fetchColumn()===1;}

    private function dateFromArenaPage(string $url,?float $deadline=null): array{try{$p=McaArenaParser::arenaPage((string)$this->httpGet($url,$deadline)['body']);return ['event_start_at'=>$p['event_start_at'],'event_date'=>$p['event_date'],'date_precision'=>$p['date_precision']];}catch(\Throwable){return ['event_start_at'=>null,'event_date'=>null,'date_precision'=>'unknown'];}}
    private function findArenaOnIndex(int $arenaId,float $deadline): ?array{for($page=1;$page<=250&&microtime(true)<$deadline-6;$page++){$parsed=McaIndexParser::parse((string)$this->httpGet($this->indexUrl($page),$deadline)['body'],$page);if($parsed['events']===[])return null;$oldest=PHP_INT_MAX;foreach($parsed['events'] as $e){$id=(int)$e['arena_id'];$oldest=min($oldest,$id);if($id===$arenaId)return ['event_start_at'=>$e['event_start_at'],'event_date'=>$e['event_date'],'date_precision'=>$e['date_precision']];}if($oldest<$arenaId||empty($parsed['has_next']))return null;}return null;}
    private function indexUrl(int $page): string{$base='https://www.chess.com/club/live-tournaments/'.rawurlencode($this->clubSlug).'?type=multi';return $page<=1?$base:$base.'&page='.$page;}
    private function dimensionUrl(string $arena,string $kind,int $page): string{$x=['clubs'=>1,'players'=>1,'pairings'=>1];$x[$kind]=$page;return rtrim($arena,'?&').'?' . http_build_query($x,'','&',PHP_QUERY_RFC3986);}

    private function httpGet(string $url,?float $deadline=null): array
    {
        $this->waitForRequestSlot();
        $remaining=$deadline===null?8.0:max(1.0,$deadline-microtime(true)-0.75);
        $timeout=max(1,min(8,(int)floor($remaining)));
        $connect=max(1,min(5,$timeout));
        $body='';$status=0;
        if(function_exists('curl_init')){
            $ch=curl_init($url);if($ch===false)throw new \RuntimeException('Unable to initialize MCA HTTP client.');
            curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_MAXREDIRS=>5,CURLOPT_CONNECTTIMEOUT=>$connect,CURLOPT_TIMEOUT=>$timeout,CURLOPT_USERAGENT=>'PromoteToKing/2.10.9 MCA Arena Acquisition (+https://www.promotetoking.org)',CURLOPT_HTTPHEADER=>['Accept: text/html,text/csv;q=0.9,*/*;q=0.5','Accept-Language: en-US,en;q=0.8']]);
            $raw=curl_exec($ch);if($raw===false){$e=curl_error($ch);curl_close($ch);throw new \RuntimeException('MCA fetch failed: '.$e);}$body=(string)$raw;$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);
        }else{
            $ctx=stream_context_create(['http'=>['method'=>'GET','timeout'=>$timeout,'ignore_errors'=>true,'header'=>"User-Agent: PromoteToKing/2.10.9 MCA Arena Acquisition\r\nAccept: text/html,text/csv;q=0.9,*/*;q=0.5\r\nAccept-Language: en-US,en;q=0.8\r\n"]]);$raw=@file_get_contents($url,false,$ctx);$body=$raw===false?'':(string)$raw;foreach($http_response_header??[] as $h)if(preg_match('~^HTTP/\S+\s+(\d+)~i',$h,$m))$status=(int)$m[1];
        }
        if($status<200||$status>=300)throw new \RuntimeException('MCA fetch returned HTTP '.$status.' for '.$url);
        return ['status'=>$status,'body'=>$body,'url'=>$url];
    }

    private function waitForRequestSlot(): void{$this->ensureState();$q=$this->pdo->prepare('SELECT last_request_at FROM p2k_lr_sync_state WHERE club_slug=?');$q->execute([$this->clubSlug]);$last=(string)($q->fetchColumn()?:'');if($last!==''){$stamp=(float)(strtotime(substr($last,0,19).' UTC')?:0);$micro=0.0;if(preg_match('/\.(\d+)/',$last,$m))$micro=(float)('0.'.substr($m[1],0,6));$elapsed=microtime(true)-($stamp+$micro);if($elapsed<1.0)usleep((int)ceil((1.0-$elapsed)*1000000));}$this->pdo->prepare('UPDATE p2k_lr_sync_state SET last_request_at=UTC_TIMESTAMP(6),request_count=request_count+1,updated_at=UTC_TIMESTAMP() WHERE club_slug=?')->execute([$this->clubSlug]);}
    private function withGlobalLock(callable $cb): mixed{$key='p2k:mca-sync:'.substr($this->clubSlug,0,40);$q=$this->pdo->prepare('SELECT GET_LOCK(?,0)');$q->execute([$key]);if((int)$q->fetchColumn()!==1)throw new ApiException('Another MCA source synchronization job is already active.',409,'MCA_SYNC_BUSY');try{return $cb();}finally{try{$r=$this->pdo->prepare('SELECT RELEASE_LOCK(?)');$r->execute([$key]);}catch(\Throwable){}}}
    private function ensureState(): void{$this->pdo->prepare("INSERT IGNORE INTO p2k_lr_sync_state(club_slug,status,phase,updated_at) VALUES(?,'idle','idle',UTC_TIMESTAMP())")->execute([$this->clubSlug]);}
    private function stateRow(): array{$q=$this->pdo->prepare('SELECT * FROM p2k_lr_sync_state WHERE club_slug=?');$q->execute([$this->clubSlug]);return $q->fetch(PDO::FETCH_ASSOC)?:[];}
    private function ensureStorage(): void{if(!is_dir($this->storageDir)&&!mkdir($this->storageDir,0770,true)&&!is_dir($this->storageDir))throw new \RuntimeException('Unable to create MCA upload directory.');}
    private function fileIdentity(array $f): ?array{$slug=trim((string)($f['arena_slug']??''));if($slug==='')$slug=preg_replace('/\.csv$/i','',basename((string)($f['original_name']??'')))??'';$id=is_numeric($f['arena_id']??null)?(int)$f['arena_id']:0;if($id<=0&&preg_match('/-(\d+)$/',$slug,$m))$id=(int)$m[1];if($id<=0||$slug==='')return null;$url=trim((string)($f['event_url']??''))?:'https://www.chess.com/tournament/live/arena/'.$slug;return ['arena_id'=>$id,'arena_slug'=>$slug,'arena_url'=>$url];}
}
